<?php

declare(strict_types=1);

namespace Flexibill\NavBundle\Enum;

use App\AppBundle\Enum\AbstractEnum;

/**
 * Class GeneralErrorCodeEnum
 * @package Flexibill\NavBundle\Enum
 */
class GeneralErrorCodeEnum extends AbstractEnum
{
    const SCHEMA_VIOLATION = 'SCHEMA_VIOLATION';
    const DUPLICATE_IN_REQUEST = 'DUPLICATE_IN_REQUEST';
    const COMPRESSION_TOLERANCE_EXCEEDED = 'COMPRESSION_TOLERANCE_EXCEEDED';
    const DECOMPRESSION_ERROR = 'DECOMPRESSION_ERROR';
    const CREATE_WITH_BATCH_INVOICE_FOUND = 'CREATE_WITH_BATCH_INVOICE_FOUND';
    const MULTIPLE_INDICES_WITH_BATCH_INVOICE_FOUND = 'MULTIPLE_INDICES_WITH_BATCH_INVOICE_FOUND';
    const DUPLICATE_IN_INVOICE_REFERENCE = 'DUPLICATE_IN_INVOICE_REFERENCE';
    const BATCH_INDEX_NOT_SEQUENTIAL = 'BATCH_INDEX_NOT_SEQUENTIAL';
    const BATCH_INVOICE_CARDINALITY_ERROR = 'BATCH_INVOICE_CARDINALITY_ERROR';
    const DUPLICATE_INVOICE_LINE_CREATION = 'DUPLICATE_INVOICE_LINE_CREATION';
}
