<?php

declare(strict_types=1);

namespace Flexibill\NavBundle\Enum;

/**
 * Class InvoiceStatusValidationErrorEnum
 * @package Flexibill\NavBundle\Enum
 */
class InvoiceStatusValidationErrorEnum
{
    const SUPPLIER_TAX_NUMBER_MISMATCH = 'SUPPLIER_TAX_NUMBER_MISMATCH';
    const INVOICE_NUMBER_NOT_UNIQUE = 'INVOICE_NUMBER_NOT_UNIQUE';
    const LINE_NUMBER_NOT_SEQUENTIAL = 'LINE_NUMBER_NOT_SEQUENTIAL';
    const INVOICE_LINE_MISSING = 'INVOICE_LINE_MISSING';
    const INVALID_INVOICE_REFERENCE = 'INVALID_INVOICE_REFERENCE';
    const INVOICE_TYPE_MISMATCH = 'INVOICE_TYPE_MISMATCH';
    const INVOICE_LINE_ALREADY_EXISTS = 'INVOICE_LINE_ALREADY_EXISTS';
    const INVALID_ANNULMENT_REFERENCE = 'INVALID_ANNULMENT_REFERENCE';
    const ANNULMENT_IN_PROGRESS = 'ANNULMENT_IN_PROGRESS';
    const CUSTOMER_NOT_ASSIGNED = 'CUSTOMER_NOT_ASSIGNED';
    const REQUEST_VERSION_REFERENCE_ERROR = 'REQUEST_VERSION_REFERENCE_ERROR';
    const LINE_NUMBER_REFERENCE_NOT_UNIQUE = 'LINE_NUMBER_REFERENCE_NOT_UNIQUE';
    const MANDATORY_LINE_CONTENT_MISSING = 'MANDATORY_LINE_CONTENT_MISSING';
    const INVALID_VAT_DATA = 'INVALID_VAT_DATA';
    const MULTIPLE_INVOICES_FOUND = 'MULTIPLE_INVOICES_FOUND';
    const MODIFICATION_INDEX_NOT_UNIQUE = 'MODIFICATION_INDEX_NOT_UNIQUE';
    const CUSTOMER_INFO_MISSING = 'CUSTOMER_INFO_MISSING';
    const INVOICE_REFERENCE_EXPECTED = 'INVOICE_REFERENCE_EXPECTED';
    const INVOICE_REFERENCE_NOT_EXPECTED = 'INVOICE_REFERENCE_NOT_EXPECTED';
    const MODIFY_WITHOUT_MASTER_MISMATCH = 'MODIFY_WITHOUT_MASTER_MISMATCH';
    const LINE_MODIFICATION_EXPECTED = 'LINE_MODIFICATION_EXPECTED';
    const LINE_MODIFICATION_NOT_EXPECTED = 'LINE_MODIFICATION_NOT_EXPECTED';
    const CUSTOMER_NOT_IDENTICAL= 'CUSTOMER_NOT_IDENTICAL';
    const CUSTOMER_DATA_NOT_EXPECTED = 'CUSTOMER_DATA_NOT_EXPECTED';
    const CUSTOMER_DATA_EXPECTED = 'CUSTOMER_DATA_EXPECTED';
    const ELECTRONIC_INVOICE_HASH_EXPECTED = 'ELECTRONIC_INVOICE_HASH_EXPECTED';
    const INVALID_INVOICE_HASH_CRYPTO = 'INVALID_INVOICE_HASH_CRYPTO';
    const INVALID_INVOICE_HASH = 'INVALID_INVOICE_HASH';
    const INVOICE_APPEARANCE_MISMATCH = 'INVOICE_APPEARANCE_MISMATCH';
    const ELECTRONIC_INVOICE_ANNULMENT_NOT_ALLOWED = 'ELECTRONIC_INVOICE_ANNULMENT_NOT_ALLOWED';
    const INVALID_LINE_VAT_EXEMPTION_CODE = 'INVALID_LINE_VAT_EXEMPTION_CODE';
    const INVALID_SUMMARY_VAT_EXEMPTION_CODE = 'INVALID_SUMMARY_VAT_EXEMPTION_CODE';
    const INVALID_LINE_VAT_OUT_OF_SCOPE_CODE = 'INVALID_LINE_VAT_OUT_OF_SCOPE_CODE';
    const INVALID_SUMMARY_VAT_OUT_OF_SCOPE_CODE = 'INVALID_SUMMARY_VAT_OUT_OF_SCOPE_CODE';
    const INCOMPLETE_ELECTRONIC_INVOICE_REFERENCE = 'INCOMPLETE_ELECTRONIC_INVOICE_REFERENCE';
    const INVALID_LINE_VAT_AMOUNT_MISMATCH_CODE = 'INVALID_LINE_VAT_AMOUNT_MISMATCH_CODE';
    const INVALID_SUMMARY_VAT_AMOUNT_MISMATCH_CODE = 'INVALID_SUMMARY_VAT_AMOUNT_MISMATCH_CODE';
    const INVOICE_COMPLETENESS_MERGED_ITEM_INDICATOR_MISMATCH = 'INVOICE_COMPLETENESS_MERGED_ITEM_INDICATOR_MISMATCH';
    const INVOICE_COMPLETENESS_PRIVATE_PERSON_INDICATOR_MISMATCH = 'INVOICE_COMPLETENESS_PRIVATE_PERSON_INDICATOR_MISMATCH';
    const INVOICE_COMPLETENESS_NOT_ALLOWED = 'INVOICE_COMPLETENESS_NOT_ALLOWED';
    const INVALID_LINE_VAT_RATE_NORMAL = 'INVALID_LINE_VAT_RATE_NORMAL';
    const INVALID_LINE_VAT_RATE_SIMPLIFIED = 'INVALID_LINE_VAT_RATE_SIMPLIFIED';
    const INVALID_SUMMARY_VAT_RATE_NORMAL = 'INVALID_SUMMARY_VAT_RATE_NORMAL';
    const INVALID_SUMMARY_VAT_RATE_SIMPLIFIED = 'INVALID_SUMMARY_VAT_RATE_SIMPLIFIED';
    const MISSING_CUSTOMER_DOMESTIC_TAXNUMBER = 'MISSING_CUSTOMER_DOMESTIC_TAXNUMBER';
    const CUSTOMER_COMMUNITY_TAXNUMBER_NOT_EXPECTED = 'CUSTOMER_COMMUNITY_TAXNUMBER_NOT_EXPECTED';
    const CUSTOMER_THIRD_STATE_TAXNUMBER_NOT_EXPECTED = 'CUSTOMER_THIRD_STATE_TAXNUMBER_NOT_EXPECTED';
    const INVALID_LINE_VAT_AMOUNT_MISMATCH_VAT_RATE = 'INVALID_LINE_VAT_AMOUNT_MISMATCH_VAT_RATE';
    const INVALID_SUMMARY_VAT_AMOUNT_MISMATCH_VAT_RATE = 'INVALID_SUMMARY_VAT_AMOUNT_MISMATCH_VAT_RATE';
    const DOMESTIC_TAXNUMBER_EXPECTED_REVERSE_CHARGE = 'DOMESTIC_TAXNUMBER_EXPECTED_REVERSE_CHARGE';
    const INVALID_INVOICE_NUMBER = 'INVALID_INVOICE_NUMBER';
}
