services:
  Flexibill\NavBundle\Service\ConnectionHandler:
    arguments:
      - '@jms_serializer'
      - '@Flexibill\NavBundle\Service\Connector'
      - '@monolog.logger'
      - '@Flexibill\NavBundle\Service\ManageRequestXMLMaker'
      - '@Symfony\Component\Validator\Validator\ValidatorInterface'
      - '%nav_module_software_params%'

  Flexibill\NavBundle\Service\Connector:
    arguments:
      - '@monolog.logger'
      - '%env(NAV_API_URL)%'
      - '%nav_module_enable%'

  # todo remove dependency from app bundle
  Flexibill\NavBundle\Transformer\NavXMLTransformer:
    arguments:
      - '@kernel'
      - '@monolog.logger'
      - '@App\AppBundle\Service\FileManager'

  Flexibill\NavBundle\Transformer\NavDataXMLTransformer:
    arguments:
      - '@kernel'
      - '@monolog.logger'
      - '@App\AppBundle\Service\FileManager'

  Flexibill\NavBundle\Transformer\InvoiceToUBL21PeppolTransformer:
    arguments:
      - '@kernel'
      - '@monolog.logger'
      - '@App\AppBundle\Service\FileManager'

  Flexibill\NavBundle\Service\TokenExchangeManager:

  Flexibill\NavBundle\Service\NavInvoiceParser\NavInvoiceParserFactory:
    arguments:
      - '@Flexibill\NavBundle\Service\NavInvoiceParser\NavLegacyInvoiceParser'
      - '@Flexibill\NavBundle\Service\NavInvoiceParser\NavInvoiceParser'
      - '@Flexibill\NavBundle\Service\NavInvoiceParser\NavSimplifiedInvoiceParser'

  Flexibill\NavBundle\Service\NavInvoiceRequestFactory:
    arguments:
      - '@Flexibill\NavBundle\Service\ConnectionHandler'
      - '@monolog.logger'
      - '@doctrine.orm.entity_manager'
      - '@App\InvoiceBundle\Repository\NavFetchJobRepository'

  Flexibill\NavBundle\Transformer\NavAnnulmentXMLTransformer:
    arguments:
      - '@jms_serializer'

  Flexibill\NavBundle\Transformer\InvoiceDataToPeppolTransformer:
    public: true
    arguments:
      - '@Flexibill\NavBundle\Transformer\InvoiceToUBL21PeppolTransformer'
      - '@jms_serializer'

  Flexibill\NavBundle\Service\NavInvoiceParser\NavLegacyInvoiceParser:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@monolog.logger'

  Flexibill\NavBundle\Service\NavInvoiceParser\NavInvoiceParser:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@monolog.logger'

  Flexibill\NavBundle\Service\NavInvoiceParser\NavSimplifiedInvoiceParser:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@monolog.logger'


  Flexibill\NavBundle\Service\ManageRequestXMLMaker:
    public: true
    arguments:
      - '@jms_serializer'