<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2016

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:vmf="http://www.altova.com/MapForce/UDF/vmf" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="vmf xs">
	<xsl:template name="vmf:vmf1_inputtoresult">
		<xsl:param name="input" select="/.."/>
		<xsl:choose>
			<xsl:when test="$input='E'">
				<xsl:value-of select="'VELECTRONIC'"/>
			</xsl:when>
			<xsl:when test="$input='P'">
				<xsl:value-of select="'VPAPER'"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="''"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:param name="param_DOCID" select="/.."/>
	<xsl:template match="/">
		<xsl:variable name="var1_initial" select="."/>
		<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:n0="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2" xmlns:qdt="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDataTypes-2" xmlns:sac="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2" xmlns:sbc="urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2" xmlns:udt="urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2">
			<xsl:attribute name="xsi:schemraLocation">urn:oasis:names:specification:ubl:schema:xsd:Invoice-2 file:///C:/_INTERNAL_DEVS/UBL2.1/xsd/maindoc/UBL-Invoice-2.1.xsd</xsl:attribute>
			<cbc:UBLVersionID>
				<xsl:value-of select="'2.1'"/>
			</cbc:UBLVersionID>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']">
				<xsl:variable name="var2_current" select="."/>
				<cbc:ID>
					<xsl:choose>
						<xsl:when test="(. = '')">
							<xsl:value-of select="$param_DOCID"/>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="."/>
						</xsl:otherwise>
					</xsl:choose>
				</cbc:ID>
			</xsl:for-each>

			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var3_current" select="."/>
				<cbc:IssueDate>
					<xsl:value-of select="*[local-name()='IssueDate' and namespace-uri()='']"/>
				</cbc:IssueDate>
			</xsl:for-each>

			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='IssueTime' and namespace-uri()='']">
				<xsl:variable name="var4_current" select="."/>
				<cbc:IssueTime>
					<xsl:value-of select="."/>
			    </cbc:IssueTime>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var5_current" select="."/>
				<cbc:DueDate>
					<xsl:value-of select="*[local-name()='DueDate' and namespace-uri()='']"/>
				</cbc:DueDate>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var6_current" select="."/>
				<cbc:InvoiceTypeCode>
					<xsl:attribute name="listAgencyID" namespace="">6</xsl:attribute>
					<xsl:attribute name="listAgencyName" namespace="">
						<xsl:value-of select="'United Nations Economic Commission for Europe '"/>
					</xsl:attribute>
					<xsl:value-of select="*[local-name()='InvoiceTypeCode' and namespace-uri()='']"/>
				</cbc:InvoiceTypeCode>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var7_filter" select="."/>
				<xsl:variable name="var8_nested">
					<xsl:call-template name="vmf:vmf1_inputtoresult">
						<xsl:with-param name="input" select="string(*[local-name()='OutputType' and namespace-uri()=''])"/>
					</xsl:call-template>
				</xsl:variable>
				<xsl:if test="string($var8_nested)">
					<cbc:Note>
						<xsl:variable name="var9_nested">
							<xsl:call-template name="vmf:vmf1_inputtoresult">
								<xsl:with-param name="input" select="string(*[local-name()='OutputType' and namespace-uri()=''])"/>
							</xsl:call-template>
						</xsl:variable>
						<xsl:value-of select="substring($var9_nested, 2)"/>
					</cbc:Note>
				</xsl:if>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='Note' and namespace-uri()='']">
				<xsl:variable name="var10_current" select="."/>
				<cbc:Note>
					<xsl:value-of select="."/>
				</cbc:Note>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='H1Note' and namespace-uri()='']">
				<xsl:variable name="var11_current" select="."/>
				<cbc:Note>
					<xsl:value-of select="."/>
				</cbc:Note>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='H2Note' and namespace-uri()='']">
				<xsl:variable name="var12_current" select="."/>
				<cbc:Note>
					<xsl:value-of select="."/>
				</cbc:Note>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='F1Note' and namespace-uri()='']">
				<xsl:variable name="var13_current" select="."/>
				<cbc:Note>
					<xsl:value-of select="."/>
				</cbc:Note>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='F2Note' and namespace-uri()='']">
				<xsl:variable name="var14_current" select="."/>
				<cbc:Note>
					<xsl:value-of select="."/>
				</cbc:Note>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='ModifyWithoutMaster' and namespace-uri()='']">
				<xsl:variable name="var15_current" select="."/>
				<cbc:Note>
					<xsl:value-of select="boolean(translate(normalize-space(string(.)), ' 0false', ''))"/>
				</cbc:Note>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='cashAccounting' and namespace-uri()='']">
				<xsl:variable name="var132_current" select="."/>
				<cbc:Note>
					<xsl:value-of select="concat('cashAccounting:', (boolean(translate(normalize-space(string(.)), ' 0false', ''))))"/>
				</cbc:Note>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='selfBilling' and namespace-uri()='']">
				<xsl:variable name="var133_current" select="."/>
				<cbc:Note>
					<xsl:value-of select="concat('selfBilling:', (boolean(translate(normalize-space(string(.)), ' 0false', ''))))"/>
				</cbc:Note>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var16_current" select="."/>
				<cbc:TaxPointDate>
					<xsl:value-of select="*[local-name()='TaxPointDate' and namespace-uri()='']"/>
				</cbc:TaxPointDate>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var17_current" select="."/>
				<cbc:DocumentCurrencyCode>
					<xsl:value-of select="*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
				</cbc:DocumentCurrencyCode>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='InvoicePeriod' and namespace-uri()='']">
				<xsl:variable name="var18_current" select="."/>
				<cac:InvoicePeriod>
					<xsl:for-each select="*[local-name()='StartDate' and namespace-uri()='']">
						<xsl:variable name="var19_current" select="."/>
						<cbc:StartDate>
							<xsl:value-of select="."/>
						</cbc:StartDate>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='EndDate' and namespace-uri()='']">
						<xsl:variable name="var20_current" select="."/>
						<cbc:EndDate>
							<xsl:value-of select="."/>
						</cbc:EndDate>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='Description' and namespace-uri()='']">
						<xsl:variable name="var21_current" select="."/>
						<cbc:Description>
							<xsl:value-of select="."/>
						</cbc:Description>
					</xsl:for-each>
				</cac:InvoicePeriod>
			</xsl:for-each>
			<cac:OrderReference>
				<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='OrderReference' and namespace-uri()='']">
					<xsl:variable name="var22_current" select="."/>
					<cbc:ID>
						<xsl:value-of select="."/>
					</cbc:ID>
				</xsl:for-each>
			</cac:OrderReference>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='BillingReference' and namespace-uri()='']">
				<xsl:variable name="var23_current" select="."/>
				<cac:BillingReference>
					<xsl:for-each select="*[local-name()='InvoiceDocumentReference' and namespace-uri()='']">
						<xsl:variable name="var24_current" select="."/>
						<cac:InvoiceDocumentReference>
							<cbc:ID>
								<xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
							</cbc:ID>
							<cbc:DocumentDescription>
								<xsl:value-of select="*[local-name()='DocumentDescription' and namespace-uri()='']"/>
							</cbc:DocumentDescription>
						</cac:InvoiceDocumentReference>
					</xsl:for-each>
				</cac:BillingReference>
			</xsl:for-each>
			<cac:AdditionalDocumentReference>
				<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']">
					<xsl:variable name="var25_current" select="."/>
					<cbc:ID>
						<xsl:value-of select="."/>
					</cbc:ID>
				</xsl:for-each>
			</cac:AdditionalDocumentReference>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var26_current" select="."/>
				<cac:AccountingSupplierParty>
					<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='AdditionalAccountID' and namespace-uri()='']">
						<xsl:variable name="var27_current" select="."/>
						<cbc:AdditionalAccountID>
							<xsl:value-of select="."/>
						</cbc:AdditionalAccountID>
					</xsl:for-each>
					<cac:Party>
						<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='WebsiteURL' and namespace-uri()='']">
							<xsl:variable name="var28_current" select="."/>
							<cbc:WebsiteURI>
								<xsl:value-of select="."/>
							</cbc:WebsiteURI>
						</xsl:for-each>
						<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyIdentification' and namespace-uri()='']">
							<xsl:variable name="var29_current" select="."/>
							<cac:PartyIdentification>
								<cbc:ID>
									<xsl:value-of select="."/>
								</cbc:ID>
							</cac:PartyIdentification>
						</xsl:for-each>
						<cac:PartyName>
							<cbc:Name>
								<xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyName' and namespace-uri()='']"/>
							</cbc:Name>
						</cac:PartyName>
						<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PostalAddress' and namespace-uri()='']">
							<xsl:variable name="var30_current" select="."/>
							<cac:PostalAddress>
								<xsl:for-each select="*[local-name()='Floor' and namespace-uri()='']">
									<xsl:variable name="var31_current" select="."/>
									<cbc:Floor>
										<xsl:value-of select="."/>
									</cbc:Floor>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='Room' and namespace-uri()='']">
									<xsl:variable name="var32_current" select="."/>
									<cbc:Room>
										<xsl:value-of select="."/>
									</cbc:Room>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='StreetName' and namespace-uri()='']">
									<xsl:variable name="var33_current" select="."/>
									<cbc:StreetName>
										<xsl:value-of select="."/>
									</cbc:StreetName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AdditionalStreetName' and namespace-uri()='']">
									<xsl:variable name="var34_current" select="."/>
									<cbc:AdditionalStreetName>
										<xsl:value-of select="."/>
									</cbc:AdditionalStreetName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='BlockName' and namespace-uri()='']">
									<xsl:variable name="var35_current" select="."/>
									<cbc:BlockName>
										<xsl:value-of select="."/>
									</cbc:BlockName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='BuildingNumber' and namespace-uri()='']">
									<xsl:variable name="var36_current" select="."/>
									<cbc:BuildingNumber>
										<xsl:value-of select="."/>
									</cbc:BuildingNumber>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='CityName' and namespace-uri()='']">
									<xsl:variable name="var37_current" select="."/>
									<cbc:CityName>
										<xsl:value-of select="."/>
									</cbc:CityName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='PostalZone' and namespace-uri()='']">
									<xsl:variable name="var38_current" select="."/>
									<cbc:PostalZone>
										<xsl:value-of select="."/>
									</cbc:PostalZone>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='District' and namespace-uri()='']">
									<xsl:variable name="var39_current" select="."/>
									<cbc:District>
										<xsl:value-of select="."/>
									</cbc:District>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AddressLine' and namespace-uri()='']">
									<xsl:variable name="var40_current" select="."/>
									<cac:AddressLine>
										<cbc:Line>
											<xsl:value-of select="."/>
										</cbc:Line>
									</cac:AddressLine>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='Country' and namespace-uri()='']">
									<xsl:variable name="var41_current" select="."/>
									<cac:Country>
										<cbc:IdentificationCode>
											<xsl:value-of select="*[local-name()='IdentificationCode' and namespace-uri()='']"/>
										</cbc:IdentificationCode>
										<cbc:Name>
											<xsl:value-of select="*[local-name()='Name' and namespace-uri()='']"/>
										</cbc:Name>
									</cac:Country>
								</xsl:for-each>
							</cac:PostalAddress>
						</xsl:for-each>
						<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyTaxScheme' and namespace-uri()='']">
							<xsl:variable name="var42_current" select="."/>
							<cac:PartyTaxScheme>
								<cbc:CompanyID>
									<xsl:value-of select="*[local-name()='CompanyID' and namespace-uri()='']"/>
								</cbc:CompanyID>
								<cac:TaxScheme>
									<cbc:ID>
										<xsl:value-of select="*[local-name()='TaxScheme' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
									</cbc:ID>
								</cac:TaxScheme>
							</cac:PartyTaxScheme>
						</xsl:for-each>
						<cac:PartyLegalEntity>
							<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationName' and namespace-uri()='']">
								<xsl:variable name="var43_current" select="."/>
								<cbc:RegistrationName>
									<xsl:value-of select="."/>
								</cbc:RegistrationName>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='CompanyID' and namespace-uri()='']">
								<xsl:variable name="var44_current" select="."/>
								<cbc:CompanyID>
									<xsl:value-of select="."/>
								</cbc:CompanyID>
							</xsl:for-each>
							<cac:RegistrationAddress>
								<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Floor' and namespace-uri()='']">
									<xsl:variable name="var45_current" select="."/>
									<cbc:Floor>
										<xsl:value-of select="."/>
									</cbc:Floor>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Room' and namespace-uri()='']">
									<xsl:variable name="var46_current" select="."/>
									<cbc:Room>
										<xsl:value-of select="."/>
									</cbc:Room>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='StreetName' and namespace-uri()='']">
									<xsl:variable name="var47_current" select="."/>
									<cbc:StreetName>
										<xsl:value-of select="."/>
									</cbc:StreetName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='AdditionalStreetName' and namespace-uri()='']">
									<xsl:variable name="var48_current" select="."/>
									<cbc:AdditionalStreetName>
										<xsl:value-of select="."/>
									</cbc:AdditionalStreetName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='BlockName' and namespace-uri()='']">
									<xsl:variable name="var49_current" select="."/>
									<cbc:BlockName>
										<xsl:value-of select="."/>
									</cbc:BlockName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='BuildingNumber' and namespace-uri()='']">
									<xsl:variable name="var50_current" select="."/>
									<cbc:BuildingNumber>
										<xsl:value-of select="."/>
									</cbc:BuildingNumber>
								</xsl:for-each>
								<cbc:CityName>
									<xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='CityName' and namespace-uri()='']"/>
								</cbc:CityName>
								<cbc:PostalZone>
									<xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='PostalZone' and namespace-uri()='']"/>
								</cbc:PostalZone>
								<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='District' and namespace-uri()='']">
									<xsl:variable name="var51_current" select="."/>
									<cbc:District>
										<xsl:value-of select="."/>
									</cbc:District>
								</xsl:for-each>
								<cac:AddressLine>
									<cbc:Line>
										<xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='AddressLine' and namespace-uri()='']"/>
									</cbc:Line>
								</cac:AddressLine>
								<cac:Country>
									<cbc:IdentificationCode>
										<xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='IdentificationCode' and namespace-uri()='']"/>
									</cbc:IdentificationCode>
									<cbc:Name>
										<xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
									</cbc:Name>
								</cac:Country>
							</cac:RegistrationAddress>
						</cac:PartyLegalEntity>
						<xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='Contact' and namespace-uri()='']">
							<xsl:variable name="var52_current" select="."/>
							<cac:Contact>
								<xsl:for-each select="*[local-name()='Telephone' and namespace-uri()='']">
									<xsl:variable name="var53_current" select="."/>
									<cbc:Telephone>
										<xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="."/>
										</xsl:if>
									</cbc:Telephone>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='Telefax' and namespace-uri()='']">
									<xsl:variable name="var54_current" select="."/>
									<cbc:Telefax>
										<xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="."/>
										</xsl:if>
									</cbc:Telefax>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='ElectronicMail' and namespace-uri()='']">
									<xsl:variable name="var55_current" select="."/>
									<cbc:ElectronicMail>
										<xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="."/>
										</xsl:if>
									</cbc:ElectronicMail>
								</xsl:for-each>
							</cac:Contact>
						</xsl:for-each>
					</cac:Party>
				</cac:AccountingSupplierParty>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var56_current" select="."/>
				<cac:AccountingCustomerParty>
					<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='AdditionalAccountID' and namespace-uri()='']">
						<xsl:variable name="var57_current" select="."/>
						<cbc:AdditionalAccountID>
							<xsl:value-of select="."/>
						</cbc:AdditionalAccountID>
					</xsl:for-each>
					<cac:Party>
						<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='WebsiteURL' and namespace-uri()='']">
							<xsl:variable name="var58_current" select="."/>
							<cbc:WebsiteURI>
								<xsl:value-of select="."/>
							</cbc:WebsiteURI>
						</xsl:for-each>
						<cbc:EndpointID>
							<xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyName' and namespace-uri()='']"/>
						</cbc:EndpointID>
						<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyIdentification' and namespace-uri()='']">
							<xsl:variable name="var59_current" select="."/>
							<cac:PartyIdentification>
								<cbc:ID>
									<xsl:value-of select="."/>
								</cbc:ID>
							</cac:PartyIdentification>
						</xsl:for-each>
						<cac:PartyName>
							<cbc:Name>
								<xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyName' and namespace-uri()='']"/>
							</cbc:Name>
						</cac:PartyName>
						<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PostalAddress' and namespace-uri()='']">
							<xsl:variable name="var60_current" select="."/>
							<cac:PostalAddress>
								<xsl:for-each select="*[local-name()='Floor' and namespace-uri()='']">
									<xsl:variable name="var61_current" select="."/>
									<cbc:Floor>
										<xsl:value-of select="."/>
									</cbc:Floor>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='Room' and namespace-uri()='']">
									<xsl:variable name="var62_current" select="."/>
									<cbc:Room>
										<xsl:value-of select="."/>
									</cbc:Room>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='StreetName' and namespace-uri()='']">
									<xsl:variable name="var63_current" select="."/>
									<cbc:StreetName>
										<xsl:value-of select="."/>
									</cbc:StreetName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AdditionalStreetName' and namespace-uri()='']">
									<xsl:variable name="var64_current" select="."/>
									<cbc:AdditionalStreetName>
										<xsl:value-of select="."/>
									</cbc:AdditionalStreetName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='BlockName' and namespace-uri()='']">
									<xsl:variable name="var65_current" select="."/>
									<cbc:BlockName>
										<xsl:value-of select="."/>
									</cbc:BlockName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='BuildingNumber' and namespace-uri()='']">
									<xsl:variable name="var66_current" select="."/>
									<cbc:BuildingNumber>
										<xsl:value-of select="."/>
									</cbc:BuildingNumber>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='CityName' and namespace-uri()='']">
									<xsl:variable name="var67_current" select="."/>
									<cbc:CityName>
										<xsl:value-of select="."/>
									</cbc:CityName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='PostalZone' and namespace-uri()='']">
									<xsl:variable name="var68_current" select="."/>
									<cbc:PostalZone>
										<xsl:value-of select="."/>
									</cbc:PostalZone>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='District' and namespace-uri()='']">
									<xsl:variable name="var69_current" select="."/>
									<cbc:District>
										<xsl:value-of select="."/>
									</cbc:District>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AddressLine' and namespace-uri()='']">
									<xsl:variable name="var70_current" select="."/>
									<cac:AddressLine>
										<cbc:Line>
											<xsl:value-of select="."/>
										</cbc:Line>
									</cac:AddressLine>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='Country' and namespace-uri()='']">
									<xsl:variable name="var71_current" select="."/>
									<cac:Country>
										<cbc:IdentificationCode>
											<xsl:value-of select="*[local-name()='IdentificationCode' and namespace-uri()='']"/>
										</cbc:IdentificationCode>
										<cbc:Name>
											<xsl:value-of select="*[local-name()='Name' and namespace-uri()='']"/>
										</cbc:Name>
									</cac:Country>
								</xsl:for-each>
							</cac:PostalAddress>
						</xsl:for-each>
						<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyTaxScheme' and namespace-uri()='']">
							<xsl:variable name="var72_current" select="."/>
							<cac:PartyTaxScheme>
								<xsl:for-each select="*[local-name()='CompanyID' and namespace-uri()='']">
									<xsl:variable name="var73_current" select="."/>
									<cbc:CompanyID>
										<xsl:value-of select="."/>
									</cbc:CompanyID>
								</xsl:for-each>
								<cac:TaxScheme>
									<cbc:ID>
										<xsl:value-of select="*[local-name()='TaxScheme' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
									</cbc:ID>
								</cac:TaxScheme>
							</cac:PartyTaxScheme>
						</xsl:for-each>
						<cac:PartyLegalEntity>
							<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationName' and namespace-uri()='']">
								<xsl:variable name="var74_current" select="."/>
								<cbc:RegistrationName>
									<xsl:value-of select="."/>
								</cbc:RegistrationName>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='CompanyID' and namespace-uri()='']">
								<xsl:variable name="var75_current" select="."/>
								<cbc:CompanyID>
									<xsl:value-of select="."/>
								</cbc:CompanyID>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyTaxScheme' and namespace-uri()='']/*[local-name()='CompanyID' and namespace-uri()='']">
								<xsl:variable name="var76_current" select="."/>
								<cbc:CompanyLegalForm>
									<xsl:choose>
										<xsl:when test="(string-length(string(.)) &gt; 5)">
											<xsl:value-of select="'009'"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="'001'"/>
										</xsl:otherwise>
									</xsl:choose>
								</cbc:CompanyLegalForm>
							</xsl:for-each>
							<cac:RegistrationAddress>
								<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Floor' and namespace-uri()='']">
									<xsl:variable name="var77_current" select="."/>
									<cbc:Floor>
										<xsl:value-of select="."/>
									</cbc:Floor>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Room' and namespace-uri()='']">
									<xsl:variable name="var78_current" select="."/>
									<cbc:Room>
										<xsl:value-of select="."/>
									</cbc:Room>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='StreetName' and namespace-uri()='']">
									<xsl:variable name="var79_current" select="."/>
									<cbc:StreetName>
										<xsl:value-of select="."/>
									</cbc:StreetName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='AdditionalStreetName' and namespace-uri()='']">
									<xsl:variable name="var80_current" select="."/>
									<cbc:AdditionalStreetName>
										<xsl:value-of select="."/>
									</cbc:AdditionalStreetName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='BlockName' and namespace-uri()='']">
									<xsl:variable name="var81_current" select="."/>
									<cbc:BlockName>
										<xsl:value-of select="."/>
									</cbc:BlockName>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='BuildingNumber' and namespace-uri()='']">
									<xsl:variable name="var82_current" select="."/>
									<cbc:BuildingNumber>
										<xsl:value-of select="."/>
									</cbc:BuildingNumber>
								</xsl:for-each>
								<cbc:CityName>
									<xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='CityName' and namespace-uri()='']"/>
								</cbc:CityName>
								<cbc:PostalZone>
									<xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='PostalZone' and namespace-uri()='']"/>
								</cbc:PostalZone>
								<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='District' and namespace-uri()='']">
									<xsl:variable name="var83_current" select="."/>
									<cbc:District>
										<xsl:value-of select="."/>
									</cbc:District>
								</xsl:for-each>
								<cac:AddressLine>
									<cbc:Line>
										<xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='AddressLine' and namespace-uri()='']"/>
									</cbc:Line>
								</cac:AddressLine>
								<cac:Country>
									<cbc:IdentificationCode>
										<xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='IdentificationCode' and namespace-uri()='']"/>
									</cbc:IdentificationCode>
									<cbc:Name>
										<xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
									</cbc:Name>
								</cac:Country>
							</cac:RegistrationAddress>
						</cac:PartyLegalEntity>
						<xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='Contact' and namespace-uri()='']">
							<xsl:variable name="var84_current" select="."/>
							<cac:Contact>
								<xsl:for-each select="*[local-name()='Telephone' and namespace-uri()='']">
									<xsl:variable name="var85_current" select="."/>
									<cbc:Telephone>
										<xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="."/>
										</xsl:if>
									</cbc:Telephone>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='Telefax' and namespace-uri()='']">
									<xsl:variable name="var86_current" select="."/>
									<cbc:Telefax>
										<xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="."/>
										</xsl:if>
									</cbc:Telefax>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='ElectronicMail' and namespace-uri()='']">
									<xsl:variable name="var87_current" select="."/>
									<cbc:ElectronicMail>
										<xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="."/>
										</xsl:if>
									</cbc:ElectronicMail>
								</xsl:for-each>
							</cac:Contact>
						</xsl:for-each>
					</cac:Party>
				</cac:AccountingCustomerParty>
			</xsl:for-each>
			<cac:DeliveryTerms>
				<cac:DeliveryLocation>
					<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='DeliveryAddress' and namespace-uri()='']">
						<xsl:variable name="var88_current" select="."/>
						<cac:Address>
							<xsl:for-each select="*[local-name()='Floor' and namespace-uri()='']">
								<xsl:variable name="var89_current" select="."/>
								<cbc:Floor>
									<xsl:value-of select="."/>
								</cbc:Floor>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='Room' and namespace-uri()='']">
								<xsl:variable name="var90_current" select="."/>
								<cbc:Room>
									<xsl:value-of select="."/>
								</cbc:Room>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='StreetName' and namespace-uri()='']">
								<xsl:variable name="var91_current" select="."/>
								<cbc:StreetName>
									<xsl:value-of select="."/>
								</cbc:StreetName>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='AdditionalStreetName' and namespace-uri()='']">
								<xsl:variable name="var92_current" select="."/>
								<cbc:AdditionalStreetName>
									<xsl:value-of select="."/>
								</cbc:AdditionalStreetName>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='BlockName' and namespace-uri()='']">
								<xsl:variable name="var93_current" select="."/>
								<cbc:BlockName>
									<xsl:value-of select="."/>
								</cbc:BlockName>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='BuildingNumber' and namespace-uri()='']">
								<xsl:variable name="var94_current" select="."/>
								<cbc:BuildingNumber>
									<xsl:value-of select="."/>
								</cbc:BuildingNumber>
							</xsl:for-each>
							<cbc:CityName>
								<xsl:value-of select="*[local-name()='CityName' and namespace-uri()='']"/>
							</cbc:CityName>
							<cbc:PostalZone>
								<xsl:value-of select="*[local-name()='PostalZone' and namespace-uri()='']"/>
							</cbc:PostalZone>
							<xsl:for-each select="*[local-name()='District' and namespace-uri()='']">
								<xsl:variable name="var95_current" select="."/>
								<cbc:District>
									<xsl:value-of select="."/>
								</cbc:District>
							</xsl:for-each>
							<cac:AddressLine>
								<cbc:Line>
									<xsl:value-of select="*[local-name()='AddressLine' and namespace-uri()='']"/>
								</cbc:Line>
							</cac:AddressLine>
							<cac:Country>
								<cbc:IdentificationCode>
									<xsl:value-of select="*[local-name()='Country' and namespace-uri()='']/*[local-name()='IdentificationCode' and namespace-uri()='']"/>
								</cbc:IdentificationCode>
								<cbc:Name>
									<xsl:value-of select="*[local-name()='Country' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
								</cbc:Name>
							</cac:Country>
						</cac:Address>
					</xsl:for-each>
				</cac:DeliveryLocation>
			</cac:DeliveryTerms>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var96_current" select="."/>
				<cac:PaymentMeans>
					<cbc:PaymentMeansCode>
						<xsl:value-of select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PaymentMeansCode' and namespace-uri()='']"/>
					</cbc:PaymentMeansCode>
					<xsl:for-each select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayerFinancialAccount' and namespace-uri()='']">
						<xsl:variable name="var97_current" select="."/>
						<cac:PayerFinancialAccount>
							<xsl:for-each select="*[local-name()='ID' and namespace-uri()='']">
								<xsl:variable name="var98_current" select="."/>
								<cbc:ID>
									<xsl:value-of select="."/>
								</cbc:ID>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='CurrencyCode' and namespace-uri()='']">
								<xsl:variable name="var99_current" select="."/>
								<cbc:CurrencyCode>
									<xsl:value-of select="."/>
								</cbc:CurrencyCode>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='FinancialAccountExtension' and namespace-uri()='']/*[local-name()='IBAN' and namespace-uri()='']">
								<xsl:variable name="var100_current" select="."/>
								<cbc:PaymentNote>
									<xsl:value-of select="."/>
								</cbc:PaymentNote>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='FinancialInstitutionBranch' and namespace-uri()='']">
								<xsl:variable name="var101_current" select="."/>
								<cac:FinancialInstitutionBranch>
									<xsl:for-each select="*[local-name()='ID' and namespace-uri()='']">
										<xsl:variable name="var102_current" select="."/>
										<cbc:ID>
											<xsl:value-of select="."/>
										</cbc:ID>
									</xsl:for-each>
									<xsl:for-each select="*[local-name()='Name' and namespace-uri()='']">
										<xsl:variable name="var103_current" select="."/>
										<cbc:Name>
											<xsl:value-of select="."/>
										</cbc:Name>
									</xsl:for-each>
								</cac:FinancialInstitutionBranch>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='Country' and namespace-uri()='']">
								<xsl:variable name="var104_current" select="."/>
								<cac:Country>
									<xsl:for-each select="*[local-name()='IdentificationCode' and namespace-uri()='']">
										<xsl:variable name="var105_current" select="."/>
										<cbc:IdentificationCode>
											<xsl:value-of select="."/>
										</cbc:IdentificationCode>
									</xsl:for-each>
									<xsl:for-each select="*[local-name()='Name' and namespace-uri()='']">
										<xsl:variable name="var106_current" select="."/>
										<cbc:Name>
											<xsl:value-of select="."/>
										</cbc:Name>
									</xsl:for-each>
								</cac:Country>
							</xsl:for-each>
						</cac:PayerFinancialAccount>
					</xsl:for-each>
					<cac:PayeeFinancialAccount>
						<cbc:ID>
							<xsl:value-of select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayeeFinancialAccount' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
						</cbc:ID>
						<xsl:for-each select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayeeFinancialAccount' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']">
							<xsl:variable name="var107_current" select="."/>
							<cbc:Name>
								<xsl:value-of select="."/>
							</cbc:Name>
						</xsl:for-each>
						<cbc:CurrencyCode>
							<xsl:value-of select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayeeFinancialAccount' and namespace-uri()='']/*[local-name()='CurrencyCode' and namespace-uri()='']"/>
						</cbc:CurrencyCode>
						<cbc:PaymentNote>
							<xsl:value-of select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayeeFinancialAccount' and namespace-uri()='']/*[local-name()='FinancialAccountExtension' and namespace-uri()='']/*[local-name()='IBAN' and namespace-uri()='']"/>
						</cbc:PaymentNote>
						<cac:FinancialInstitutionBranch>
							<cbc:ID>
								<xsl:value-of select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayeeFinancialAccount' and namespace-uri()='']/*[local-name()='FinancialInstitutionBranch' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
							</cbc:ID>
							<cbc:Name>
								<xsl:value-of select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayeeFinancialAccount' and namespace-uri()='']/*[local-name()='FinancialInstitutionBranch' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
							</cbc:Name>
						</cac:FinancialInstitutionBranch>
						<cac:Country>
							<cbc:IdentificationCode>
								<xsl:value-of select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayeeFinancialAccount' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='IdentificationCode' and namespace-uri()='']"/>
							</cbc:IdentificationCode>
							<cbc:Name>
								<xsl:value-of select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayeeFinancialAccount' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
							</cbc:Name>
						</cac:Country>
					</cac:PayeeFinancialAccount>
				</cac:PaymentMeans>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var108_current" select="."/>
				<cac:TaxExchangeRate>
					<cbc:SourceCurrencyCode>
						<xsl:value-of select="*[local-name()='PricingExchangeRate' and namespace-uri()='']/*[local-name()='SourceCurrencyCode' and namespace-uri()='']"/>
					</cbc:SourceCurrencyCode>
					<cbc:TargetCurrencyCode>
						<xsl:value-of select="*[local-name()='PricingExchangeRate' and namespace-uri()='']/*[local-name()='TargetCurrencyCode' and namespace-uri()='']"/>
					</cbc:TargetCurrencyCode>
					<cbc:CalculationRate>
						<xsl:value-of select="number(*[local-name()='PricingExchangeRate' and namespace-uri()='']/*[local-name()='CalculationRate' and namespace-uri()=''])"/>
					</cbc:CalculationRate>
					<cbc:MathematicOperatorCode>
						<xsl:value-of select="*[local-name()='PricingExchangeRate' and namespace-uri()='']/*[local-name()='MathematicOperatorCode' and namespace-uri()='']"/>
					</cbc:MathematicOperatorCode>
				</cac:TaxExchangeRate>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var109_current" select="."/>
				<cac:TaxTotal>
					<cbc:TaxAmount>
						<xsl:attribute name="currencyID" namespace="">
							<xsl:value-of select="*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
						</xsl:attribute>
						<xsl:value-of select="number(*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxAmount' and namespace-uri()=''])"/>
					</cbc:TaxAmount>
					<cbc:TaxAmountInOriginalCurrency>
						<xsl:value-of select="number(*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxAmountInOriginalCurrency' and namespace-uri()=''])"/>
					</cbc:TaxAmountInOriginalCurrency>
					<cbc:RoundingAmount>
						<xsl:attribute name="currencyID" namespace="">
							<xsl:value-of select="*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
						</xsl:attribute>
					</cbc:RoundingAmount>
					<xsl:for-each select="*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxSubtotal' and namespace-uri()='']">
						<xsl:variable name="var110_current" select="."/>
						<cac:TaxSubtotal>
							<cbc:TaxableAmount>
								<xsl:attribute name="currencyID" namespace="">
									<xsl:value-of select="$var109_current/*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
								</xsl:attribute>
								<xsl:value-of select="number(*[local-name()='TaxableAmount' and namespace-uri()=''])"/>
							</cbc:TaxableAmount>
							<cbc:TaxAmount>
								<xsl:attribute name="currencyID" namespace="">
									<xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
								</xsl:attribute>
								<xsl:value-of select="number(*[local-name()='TaxAmount' and namespace-uri()=''])"/>
							</cbc:TaxAmount>
							<cbc:Percent>
								<xsl:value-of select="number(*[local-name()='Percent' and namespace-uri()=''])"/>
							</cbc:Percent>
							<cac:TaxCategory>
								<cbc:Name>
									<xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
								</cbc:Name>
								<cac:TaxScheme>
									<cbc:ID>
										<xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='TaxScheme' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
									</cbc:ID>
								</cac:TaxScheme>
							</cac:TaxCategory>
						</cac:TaxSubtotal>
					</xsl:for-each>
				</cac:TaxTotal>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var111_current" select="."/>
				<cac:LegalMonetaryTotal>
					<cbc:LineExtensionAmount>
						<xsl:attribute name="currencyID" namespace="">
							<xsl:value-of select="*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
						</xsl:attribute>
						<xsl:value-of select="number(*[local-name()='LegalMonetaryTotal' and namespace-uri()='']/*[local-name()='LineExtensionAmount' and namespace-uri()=''])"/>
					</cbc:LineExtensionAmount>
					<cbc:TaxExclusiveAmount>
						<xsl:attribute name="currencyID" namespace="">
							<xsl:value-of select="*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
						</xsl:attribute>
						<xsl:value-of select="number(*[local-name()='LegalMonetaryTotal' and namespace-uri()='']/*[local-name()='TaxExclusiveAmount' and namespace-uri()=''])"/>
					</cbc:TaxExclusiveAmount>
					<cbc:TaxInclusiveAmount>
						<xsl:attribute name="currencyID" namespace="">
							<xsl:value-of select="*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
						</xsl:attribute>
						<xsl:value-of select="number(*[local-name()='LegalMonetaryTotal' and namespace-uri()='']/*[local-name()='TaxInclusiveAmount' and namespace-uri()=''])"/>
					</cbc:TaxInclusiveAmount>
					<cbc:PayableAmount>
						<xsl:attribute name="currencyID" namespace="">
							<xsl:value-of select="*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
						</xsl:attribute>
						<xsl:value-of select="number(*[local-name()='LegalMonetaryTotal' and namespace-uri()='']/*[local-name()='PayableAmount' and namespace-uri()=''])"/>
					</cbc:PayableAmount>
				</cac:LegalMonetaryTotal>
			</xsl:for-each>
			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:variable name="var112_current" select="."/>
				<xsl:for-each select="*[local-name()='InvoiceLine' and namespace-uri()='']">
					<xsl:variable name="var113_current" select="."/>
					<cac:InvoiceLine>
						<cbc:ID>
							<xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
						</cbc:ID>
						<cbc:InvoicedQuantity>
							<xsl:attribute name="unitCode" namespace="">
								<xsl:value-of select="*[local-name()='UnitCode' and namespace-uri()='']"/>
							</xsl:attribute>
							<xsl:value-of select="number(*[local-name()='InvoicedQuantity' and namespace-uri()=''])"/>
						</cbc:InvoicedQuantity>
						<xsl:if test="*[local-name()='OwnUnitCode' and namespace-uri()=''] != ''">
							<cbc:OwnUnitCode>
								<xsl:value-of select="*[local-name()='OwnUnitCode' and namespace-uri()='']"/>
							</cbc:OwnUnitCode>
						</xsl:if>

						<cbc:AdvanceIndicator>
							<xsl:value-of select="*[local-name()='AdvanceIndicator' and namespace-uri()='']"/>
						</cbc:AdvanceIndicator>
						<cbc:LineExtensionAmount>
							<xsl:attribute name="currencyID" namespace="">
								<xsl:value-of select="$var112_current/*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
							</xsl:attribute>
							<xsl:value-of select="number(*[local-name()='LineExtensionAmount' and namespace-uri()=''])"/>
						</cbc:LineExtensionAmount>
						<xsl:for-each select="*[local-name()='TaxPointDate' and namespace-uri()='']">
							<xsl:variable name="var114_current" select="."/>
							<cbc:TaxPointDate>
								<xsl:value-of select="."/>
							</cbc:TaxPointDate>
						</xsl:for-each>
						<xsl:for-each select="*[local-name()='InvoicePeriod' and namespace-uri()='']">
							<xsl:variable name="var115_current" select="."/>
							<cac:InvoicePeriod>
								<xsl:for-each select="*[local-name()='StartDate' and namespace-uri()='']">
									<xsl:variable name="var116_current" select="."/>
									<cbc:StartDate>
										<xsl:value-of select="."/>
									</cbc:StartDate>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='EndDate' and namespace-uri()='']">
									<xsl:variable name="var117_current" select="."/>
									<cbc:EndDate>
										<xsl:value-of select="."/>
									</cbc:EndDate>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='Description' and namespace-uri()='']">
									<xsl:variable name="var118_current" select="."/>
									<cbc:Description>
										<xsl:value-of select="."/>
									</cbc:Description>
								</xsl:for-each>
							</cac:InvoicePeriod>
						</xsl:for-each>
						<xsl:for-each select="*[local-name()='BillingReference' and namespace-uri()='']">
							<xsl:variable name="var119_current" select="."/>
							<cac:BillingReference>
								<xsl:for-each select="*[local-name()='BillingReferenceLine' and namespace-uri()='']">
									<xsl:variable name="var120_current" select="."/>
									<cac:BillingReferenceLine>
										<cbc:ID>
											<xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
										</cbc:ID>
									</cac:BillingReferenceLine>
								</xsl:for-each>
							</cac:BillingReference>
						</xsl:for-each>
						<xsl:for-each select="*[local-name()='PaymentTerms' and namespace-uri()='']">
							<xsl:variable name="var121_current" select="."/>
							<cac:PaymentTerms>
								<cbc:Note>
									<xsl:value-of select="*[local-name()='Note' and namespace-uri()='']"/>
								</cbc:Note>
							</cac:PaymentTerms>
						</xsl:for-each>
						<xsl:for-each select="*[local-name()='AllowanceCharge' and namespace-uri()='']">
							<xsl:variable name="var122_current" select="."/>
							<cac:AllowanceCharge>
								<xsl:for-each select="*[local-name()='ChargeIndicator' and namespace-uri()='']">
									<xsl:variable name="var123_current" select="."/>
									<cbc:ChargeIndicator>
										<xsl:value-of select="boolean(translate(normalize-space(string(.)), ' 0false', ''))"/>
									</cbc:ChargeIndicator>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='AllowanceChargeReason' and namespace-uri()='']">
									<xsl:variable name="var124_current" select="."/>
									<cbc:AllowanceChargeReason>
										<xsl:value-of select="."/>
									</cbc:AllowanceChargeReason>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='MultiplierFactorNumeric' and namespace-uri()='']">
									<xsl:variable name="var125_current" select="."/>
									<cbc:MultiplierFactorNumeric>
										<xsl:value-of select="number(.)"/>
									</cbc:MultiplierFactorNumeric>
								</xsl:for-each>
								<xsl:for-each select="*[local-name()='Amount' and namespace-uri()='']">
									<xsl:variable name="var126_current" select="."/>
									<cbc:Amount>
										<xsl:attribute name="currencyID" namespace="">
											<xsl:value-of select="$var112_current/*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
										</xsl:attribute>
										<xsl:value-of select="number(.)"/>
									</cbc:Amount>
								</xsl:for-each>
							</cac:AllowanceCharge>
						</xsl:for-each>
						<cac:TaxTotal>
							<cbc:TaxAmount>
								<xsl:attribute name="currencyID" namespace="">
									<xsl:value-of select="$var112_current/*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
								</xsl:attribute>
								<xsl:value-of select="number(*[local-name()='TaxAmount' and namespace-uri()=''])"/>
							</cbc:TaxAmount>
							<xsl:for-each select="*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxSubtotal' and namespace-uri()='']">
								<xsl:variable name="var127_current" select="."/>
								<cac:TaxSubtotal>
									<cbc:TaxableAmount>
										<xsl:attribute name="currencyID" namespace="">
											<xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
										</xsl:attribute>
										<xsl:value-of select="number(*[local-name()='TaxableAmount' and namespace-uri()=''])"/>
									</cbc:TaxableAmount>
									<cbc:TaxAmount>
										<xsl:attribute name="currencyID" namespace="">
											<xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
										</xsl:attribute>
										<xsl:value-of select="number(*[local-name()='TaxAmount' and namespace-uri()=''])"/>
									</cbc:TaxAmount>
									<cbc:Percent>
										<xsl:value-of select="number(*[local-name()='Percent' and namespace-uri()=''])"/>
									</cbc:Percent>
									<cac:TaxCategory>
										<cbc:Name>
											<xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
										</cbc:Name>
										<cac:TaxScheme>
											<cbc:ID>
												<xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='TaxScheme' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
											</cbc:ID>
										</cac:TaxScheme>
									</cac:TaxCategory>
								</cac:TaxSubtotal>
							</xsl:for-each>
						</cac:TaxTotal>
						<cac:Item>
							<cbc:Name>
								<xsl:value-of select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
							</cbc:Name>
							<xsl:for-each select="*[local-name()='AdditionalInformation' and namespace-uri()='']">
								<xsl:variable name="var128_current" select="."/>
								<cbc:AdditionalInformation>
									<xsl:value-of select="."/>
								</cbc:AdditionalInformation>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='SellersItemIdentification' and namespace-uri()='']">
								<xsl:variable name="var129_current" select="."/>
								<cac:SellersItemIdentification>
									<xsl:for-each select="*[local-name()='ID' and namespace-uri()='']">
										<xsl:variable name="var130_current" select="."/>
										<cbc:ID>
											<xsl:value-of select="."/>
										</cbc:ID>
									</xsl:for-each>
								</cac:SellersItemIdentification>
							</xsl:for-each>
							<cac:ClassifiedTaxCategory>
								<cbc:Name>
									<xsl:value-of select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='ClassifiedTaxCategory' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
								</cbc:Name>
								<cbc:Percent>
									<xsl:value-of select="number(*[local-name()='Item' and namespace-uri()='']/*[local-name()='ClassifiedTaxCategory' and namespace-uri()='']/*[local-name()='Percent' and namespace-uri()=''])"/>
								</cbc:Percent>
								<cac:TaxScheme>
									<cbc:ID>
										<xsl:attribute name="schemeName" namespace="">UN/ECE 5153</xsl:attribute>
										<xsl:attribute name="schemeAgencyID" namespace="">6</xsl:attribute>
										<xsl:value-of select="'VAT'"/>
									</cbc:ID>
								</cac:TaxScheme>
							</cac:ClassifiedTaxCategory>
							<xsl:for-each select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='AdditionalItemProperty' and namespace-uri()='']">
								<xsl:variable name="var131_current" select="."/>
								<cac:AdditionalItemProperty>
									<cbc:ID>
										<xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
									</cbc:ID>
									<cbc:Name>
										<xsl:value-of select="*[local-name()='Name' and namespace-uri()='']"/>
									</cbc:Name>
									<cbc:Value>
										<xsl:value-of select="*[local-name()='Value' and namespace-uri()='']"/>
									</cbc:Value>
								</cac:AdditionalItemProperty>
							</xsl:for-each>
						</cac:Item>
						<cac:Price>
							<cbc:PriceAmount>
								<xsl:attribute name="currencyID" namespace="">
									<xsl:value-of select="$var112_current/*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
								</xsl:attribute>
								<xsl:value-of select="number(*[local-name()='Price' and namespace-uri()='']/*[local-name()='PriceAmount' and namespace-uri()=''])"/>
							</cbc:PriceAmount>
							<cbc:BaseQuantity>
								<xsl:value-of select="number(*[local-name()='Price' and namespace-uri()='']/*[local-name()='BaseQuantity' and namespace-uri()=''])"/>
							</cbc:BaseQuantity>
						</cac:Price>
					</cac:InvoiceLine>

				</xsl:for-each>
			</xsl:for-each>

			<xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
				<xsl:for-each select="*[local-name()='InvoiceAnnulmentType' and namespace-uri()='']">
					<cac:InvoiceAnnulmentType>
						<cbc:annulmentReference>
							<xsl:value-of select="*[local-name()='annulmentReference' and namespace-uri()='']"/>
						</cbc:annulmentReference>
						<cbc:annulmentTimestamp>
							<xsl:value-of select="*[local-name()='annulmentTimestamp' and namespace-uri()='']"/>
						</cbc:annulmentTimestamp>
						<cbc:annulmentCode>
							<xsl:value-of select="*[local-name()='annulmentCode' and namespace-uri()='']"/>
						</cbc:annulmentCode>
						<cbc:annulmentReason>
							<xsl:value-of select="*[local-name()='annulmentReason' and namespace-uri()='']"/>
						</cbc:annulmentReason>
					</cac:InvoiceAnnulmentType>
				</xsl:for-each>
			</xsl:for-each>


		</Invoice>
	</xsl:template>
</xsl:stylesheet>
