<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2020r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:vmf="http://www.altova.com/MapForce/UDF/vmf" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="vmf xs">
    <xsl:template name="vmf:vmf1_inputtoresult">
        <xsl:param name="input" select="/.."/>
        <xsl:choose>
            <xsl:when test="$input='Debit note related to goods or services'">
                <xsl:value-of select="'V80'"/>
            </xsl:when>
            <xsl:when test="$input='Metered services invoice'">
                <xsl:value-of select="'V82'"/>
            </xsl:when>
            <xsl:when test="$input='Debit note related to financial adjustments'">
                <xsl:value-of select="'V84'"/>
            </xsl:when>
            <xsl:when test="$input='SalesInvoice'">
                <xsl:value-of select="'V380'"/>
            </xsl:when>
            <xsl:when test="$input='Debit note'">
                <xsl:value-of select="'V383'"/>
            </xsl:when>
            <xsl:when test="$input='PrepaymentInvoice
'">
                <xsl:value-of select="'V386'"/>
            </xsl:when>
            <xsl:when test="$input='Factored invoice'">
                <xsl:value-of select="'V393'"/>
            </xsl:when>
            <xsl:when test="$input='Consignment invoice
'">
                <xsl:value-of select="'V395'"/>
            </xsl:when>
            <xsl:when test="$input=&quot;Insurer's invoice&quot;">
                <xsl:value-of select="'V575'"/>
            </xsl:when>
            <xsl:when test="$input=&quot;Forwarder's invoice&quot;">
                <xsl:value-of select="'V623'"/>
            </xsl:when>
            <xsl:when test="$input='Freight invoice'">
                <xsl:value-of select="'V780'"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select="''"/>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
    <xsl:template name="vmf:vmf2_inputtoresult">
        <xsl:param name="input" select="/.."/>
        <xsl:choose>
            <xsl:when test="$input='E'">
                <xsl:value-of select="'VELECTRONIC'"/>
            </xsl:when>
            <xsl:when test="$input='P'">
                <xsl:value-of select="'VPAPER'"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select="''"/>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
    <xsl:template name="vmf:vmf3_inputtoresult">
        <xsl:param name="input" select="/.."/>
        <xsl:choose>
            <xsl:when test="$input='PIECE'">
                <xsl:value-of select="'VH87'"/>
            </xsl:when>
            <xsl:when test="$input='KILOGRAM'">
                <xsl:value-of select="'VKGM'"/>
            </xsl:when>
            <xsl:when test="$input='TON'">
                <xsl:value-of select="'VTNE'"/>
            </xsl:when>
            <xsl:when test="$input='KWH'">
                <xsl:value-of select="'VD03'"/>
            </xsl:when>
            <xsl:when test="$input='DAY'">
                <xsl:value-of select="'VDAY'"/>
            </xsl:when>
            <xsl:when test="$input='HOUR'">
                <xsl:value-of select="'VHUR'"/>
            </xsl:when>
            <xsl:when test="$input='MINUTE'">
                <xsl:value-of select="'VMIN'"/>
            </xsl:when>
            <xsl:when test="$input='MONTH'">
                <xsl:value-of select="'VM36'"/>
            </xsl:when>
            <xsl:when test="$input='LITER'">
                <xsl:value-of select="'VLTR'"/>
            </xsl:when>
            <xsl:when test="$input='KILOMETER'">
                <xsl:value-of select="'VKMT'"/>
            </xsl:when>
            <xsl:when test="$input='CUBIC_METER'">
                <xsl:value-of select="'VMTQ'"/>
            </xsl:when>
            <xsl:when test="$input='METER'">
                <xsl:value-of select="'VMTR'"/>
            </xsl:when>
            <xsl:when test="$input='LINEAR_METER'">
                <xsl:value-of select="'VLM'"/>
            </xsl:when>
            <xsl:when test="$input='CARTON'">
                <xsl:value-of select="'VDZP'"/>
            </xsl:when>
            <xsl:when test="$input='PACK'">
                <xsl:value-of select="'VNMP'"/>
            </xsl:when>
            <xsl:when test="$input='OWN'">
                <xsl:value-of select="'VZZ'"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select="''"/>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
    <xsl:output method="xml" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <xsl:variable name="var1_initial" select="."/>
        <Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:n0="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2" xmlns:qdt="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDataTypes-2" xmlns:sac="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2" xmlns:sbc="urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2" xmlns:udt="urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2">
            <xsl:attribute name="xsi:schemaLocation">urn:oasis:names:specification:ubl:schema:xsd:Invoice-2 file://Mac/Home/web/altova/xsd/maindoc/UBL-Invoice-2.1.xsd</xsl:attribute>
            <cbc:CustomizationID>
                <xsl:value-of select="'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0'"/>
            </cbc:CustomizationID>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']">
                <xsl:variable name="var2_cur" select="."/>
                <cbc:ID>
                    <xsl:value-of select="."/>
                </cbc:ID>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var3_cur" select="."/>
                <cbc:IssueDate>
                    <xsl:value-of select="*[local-name()='IssueDate' and namespace-uri()='']"/>
                </cbc:IssueDate>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='IssueTime' and namespace-uri()='']">
                <xsl:variable name="var4_cur" select="."/>
                <cbc:IssueTime>
                    <xsl:value-of select="."/>
                </cbc:IssueTime>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var5_cur" select="."/>
                <cbc:DueDate>
                    <xsl:value-of select="*[local-name()='DueDate' and namespace-uri()='']"/>
                </cbc:DueDate>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var6_cur" select="."/>
                <xsl:variable name="var7_nested">
                    <xsl:call-template name="vmf:vmf1_inputtoresult">
                        <xsl:with-param name="input" select="string(*[local-name()='invoiceTypeCode' and namespace-uri()=''])"/>
                    </xsl:call-template>
                </xsl:variable>
                <xsl:if test="string($var7_nested)">
                    <cbc:InvoiceTypeCode>
                        <xsl:variable name="var8_nested">
                            <xsl:call-template name="vmf:vmf1_inputtoresult">
                                <xsl:with-param name="input" select="string(*[local-name()='invoiceTypeCode' and namespace-uri()=''])"/>
                            </xsl:call-template>
                        </xsl:variable>
                        <xsl:value-of select="substring($var8_nested, 2)"/>
                    </cbc:InvoiceTypeCode>
                </xsl:if>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='Note' and namespace-uri()='']">
                <xsl:variable name="var9_cur" select="."/>
                <cbc:Note>
                    <xsl:value-of select="."/>
                </cbc:Note>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='selfBilling' and namespace-uri()='']">
                <xsl:variable name="var10_cur" select="."/>
                <cbc:Note>
                    <xsl:value-of select="concat('selfBilling:', boolean(translate(normalize-space(string(.)), ' 0false', '')))"/>
                </cbc:Note>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='cashAccounting' and namespace-uri()='']">
                <xsl:variable name="var11_cur" select="."/>
                <cbc:Note>
                    <xsl:value-of select="concat('cashAccounting:', boolean(translate(normalize-space(string(.)), ' 0false', '')))"/>
                </cbc:Note>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='ModifyWithoutMaster' and namespace-uri()='']">
                <xsl:variable name="var12_cur" select="."/>
                <cbc:Note>
                    <xsl:value-of select="concat('modifyWithoutMaster:', boolean(translate(normalize-space(string(.)), ' 0false', '')))"/>
                </cbc:Note>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var13_cur" select="."/>
                <xsl:variable name="var14_nested">
                    <xsl:call-template name="vmf:vmf2_inputtoresult">
                        <xsl:with-param name="input" select="string(*[local-name()='OutputType' and namespace-uri()=''])"/>
                    </xsl:call-template>
                </xsl:variable>
                <xsl:if test="string($var14_nested)">
                    <cbc:Note>
                        <xsl:variable name="var15_nested">
                            <xsl:call-template name="vmf:vmf2_inputtoresult">
                                <xsl:with-param name="input" select="string(*[local-name()='OutputType' and namespace-uri()=''])"/>
                            </xsl:call-template>
                        </xsl:variable>
                        <xsl:value-of select="substring($var15_nested, 2)"/>
                    </cbc:Note>
                </xsl:if>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var16_cur" select="."/>
                <cbc:TaxPointDate>
                    <xsl:value-of select="*[local-name()='TaxPointDate' and namespace-uri()='']"/>
                </cbc:TaxPointDate>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var17_cur" select="."/>
                <cbc:DocumentCurrencyCode>
                    <xsl:value-of select="*[local-name()='DocumentCurrencyCode' and namespace-uri()='']"/>
                </cbc:DocumentCurrencyCode>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='InvoicePeriod' and namespace-uri()='']">
                <xsl:variable name="var18_cur" select="."/>
                <cac:InvoicePeriod>
                    <xsl:for-each select="*[local-name()='StartDate' and namespace-uri()='']">
                        <xsl:variable name="var19_cur" select="."/>
                        <cbc:StartDate>
                            <xsl:value-of select="."/>
                        </cbc:StartDate>
                    </xsl:for-each>
                    <xsl:for-each select="*[local-name()='EndDate' and namespace-uri()='']">
                        <xsl:variable name="var20_cur" select="."/>
                        <cbc:EndDate>
                            <xsl:value-of select="."/>
                        </cbc:EndDate>
                    </xsl:for-each>
                    <xsl:for-each select="*[local-name()='Description' and namespace-uri()='']">
                        <xsl:variable name="var21_cur" select="."/>
                        <cbc:Description>
                            <xsl:value-of select="."/>
                        </cbc:Description>
                    </xsl:for-each>
                </cac:InvoicePeriod>
            </xsl:for-each>
            <cac:OrderReference>
                <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='OrderReference' and namespace-uri()='']">
                    <xsl:variable name="var22_cur" select="."/>
                    <cbc:ID>
                        <xsl:for-each select="@schemeID">
                            <xsl:variable name="var23_cur" select="."/>
                            <xsl:attribute name="schemeID" namespace="">
                                <xsl:value-of select="."/>
                            </xsl:attribute>
                        </xsl:for-each>
                        <xsl:value-of select="."/>
                    </cbc:ID>
                </xsl:for-each>
            </cac:OrderReference>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='BillingReference' and namespace-uri()='']">
                <xsl:variable name="var24_cur" select="."/>
                <cac:BillingReference>
                    <xsl:for-each select="*[local-name()='InvoiceDocumentReference' and namespace-uri()='']">
                        <xsl:variable name="var25_cur" select="."/>
                        <cac:InvoiceDocumentReference>
                            <cbc:ID>
                                <xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
                            </cbc:ID>
                            <cbc:DocumentDescription>
                                <xsl:value-of select="*[local-name()='DocumentDescription' and namespace-uri()='']"/>
                            </cbc:DocumentDescription>
                        </cac:InvoiceDocumentReference>
                    </xsl:for-each>
                    <xsl:for-each select="*[local-name()='BillingReferenceLine' and namespace-uri()='']">
                        <xsl:variable name="var26_cur" select="."/>
                        <cac:BillingReferenceLine>
                            <cbc:ID>
                                <xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
                            </cbc:ID>
                        </cac:BillingReferenceLine>
                    </xsl:for-each>
                </cac:BillingReference>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var27_cur" select="."/>
                <cac:AccountingSupplierParty>
                    <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='AdditionalAccountID' and namespace-uri()='']">
                        <xsl:variable name="var28_cur" select="."/>
                        <cbc:AdditionalAccountID>
                            <xsl:value-of select="."/>
                        </cbc:AdditionalAccountID>
                    </xsl:for-each>
                    <cac:Party>
                        <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='WebsiteURL' and namespace-uri()='']">
                            <xsl:variable name="var29_cur" select="."/>
                            <cbc:WebsiteURI>
                                <xsl:value-of select="."/>
                            </cbc:WebsiteURI>
                        </xsl:for-each>
                        <cbc:EndpointID>
                            <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='EndpointID' and namespace-uri()='']/@schemeID">
                                <xsl:variable name="var30_cur" select="."/>
                                <xsl:attribute name="schemeID" namespace="">
                                    <xsl:value-of select="."/>
                                </xsl:attribute>
                            </xsl:for-each>
                            <xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='EndpointID' and namespace-uri()='']"/>
                        </cbc:EndpointID>
                        <cac:PartyIdentification>
                            <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyIdentification' and namespace-uri()='']">
                                <xsl:variable name="var31_cur" select="."/>
                                <cbc:ID>
                                    <xsl:value-of select="."/>
                                </cbc:ID>
                            </xsl:for-each>
                        </cac:PartyIdentification>
                        <cac:PartyName>
                            <cbc:Name>
                                <xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyName' and namespace-uri()='']"/>
                            </cbc:Name>
                        </cac:PartyName>
                        <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PostalAddress' and namespace-uri()='']">
                            <xsl:variable name="var32_cur" select="."/>
                            <cac:PostalAddress>
                                <xsl:for-each select="*[local-name()='Floor' and namespace-uri()='']">
                                    <xsl:variable name="var33_cur" select="."/>
                                    <cbc:Floor>
                                        <xsl:value-of select="."/>
                                    </cbc:Floor>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='Room' and namespace-uri()='']">
                                    <xsl:variable name="var34_cur" select="."/>
                                    <cbc:Room>
                                        <xsl:value-of select="."/>
                                    </cbc:Room>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='StreetName' and namespace-uri()='']">
                                    <xsl:variable name="var35_cur" select="."/>
                                    <cbc:StreetName>
                                        <xsl:value-of select="."/>
                                    </cbc:StreetName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AdditionalStreetName' and namespace-uri()='']">
                                    <xsl:variable name="var36_cur" select="."/>
                                    <cbc:AdditionalStreetName>
                                        <xsl:value-of select="."/>
                                    </cbc:AdditionalStreetName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='BlockName' and namespace-uri()='']">
                                    <xsl:variable name="var37_cur" select="."/>
                                    <cbc:BlockName>
                                        <xsl:value-of select="."/>
                                    </cbc:BlockName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='BuildingNumber' and namespace-uri()='']">
                                    <xsl:variable name="var38_cur" select="."/>
                                    <cbc:BuildingNumber>
                                        <xsl:value-of select="."/>
                                    </cbc:BuildingNumber>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='CityName' and namespace-uri()='']">
                                    <xsl:variable name="var39_cur" select="."/>
                                    <cbc:CityName>
                                        <xsl:value-of select="."/>
                                    </cbc:CityName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='PostalZone' and namespace-uri()='']">
                                    <xsl:variable name="var40_cur" select="."/>
                                    <cbc:PostalZone>
                                        <xsl:value-of select="."/>
                                    </cbc:PostalZone>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='District' and namespace-uri()='']">
                                    <xsl:variable name="var41_cur" select="."/>
                                    <cbc:District>
                                        <xsl:value-of select="."/>
                                    </cbc:District>
                                </xsl:for-each>
                                <cac:AddressLine>
                                    <xsl:for-each select="*[local-name()='AddressLine' and namespace-uri()='']">
                                        <xsl:variable name="var42_cur" select="."/>
                                        <cbc:Line>
                                            <xsl:value-of select="."/>
                                        </cbc:Line>
                                    </xsl:for-each>
                                </cac:AddressLine>
                                <xsl:for-each select="*[local-name()='Country' and namespace-uri()='']">
                                    <xsl:variable name="var43_cur" select="."/>
                                    <cac:Country>
                                        <cbc:IdentificationCode>
                                            <xsl:value-of select="*[local-name()='IdentificationCode' and namespace-uri()='']"/>
                                        </cbc:IdentificationCode>
                                        <cbc:Name>
                                            <xsl:value-of select="*[local-name()='Name' and namespace-uri()='']"/>
                                        </cbc:Name>
                                    </cac:Country>
                                </xsl:for-each>
                            </cac:PostalAddress>
                        </xsl:for-each>
                        <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyTaxScheme' and namespace-uri()='']">
                            <xsl:variable name="var44_cur" select="."/>
                            <cac:PartyTaxScheme>
                                <cbc:CompanyID>
                                    <xsl:choose>
                                        <xsl:when test="contains(*[local-name()='CompanyID' and namespace-uri()=''], 'EUVAT')">
                                            <xsl:value-of select="concat('HU', substring(*[local-name()='CompanyID' and namespace-uri()=''], 1, 8))"/>
                                        </xsl:when>
                                        <xsl:otherwise>
                                            <xsl:value-of select="*[local-name()='CompanyID' and namespace-uri()='']"/>
                                        </xsl:otherwise>
                                    </xsl:choose>
                                </cbc:CompanyID>
                                <cac:TaxScheme>
                                    <cbc:ID>
                                        <xsl:value-of select="*[local-name()='TaxScheme' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
                                    </cbc:ID>
                                </cac:TaxScheme>
                            </cac:PartyTaxScheme>
                        </xsl:for-each>
                        <cac:PartyLegalEntity>
                            <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationName' and namespace-uri()='']">
                                <xsl:variable name="var45_cur" select="."/>
                                <cbc:RegistrationName>
                                    <xsl:value-of select="."/>
                                </cbc:RegistrationName>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='CompanyID' and namespace-uri()='']">
                                <xsl:variable name="var46_cur" select="."/>
                                <cbc:CompanyID>
                                    <xsl:value-of select="."/>
                                </cbc:CompanyID>
                            </xsl:for-each>
                            <cac:RegistrationAddress>
                                <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Floor' and namespace-uri()='']">
                                    <xsl:variable name="var47_cur" select="."/>
                                    <cbc:Floor>
                                        <xsl:value-of select="."/>
                                    </cbc:Floor>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Room' and namespace-uri()='']">
                                    <xsl:variable name="var48_cur" select="."/>
                                    <cbc:Room>
                                        <xsl:value-of select="."/>
                                    </cbc:Room>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='StreetName' and namespace-uri()='']">
                                    <xsl:variable name="var49_cur" select="."/>
                                    <cbc:StreetName>
                                        <xsl:value-of select="."/>
                                    </cbc:StreetName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='AdditionalStreetName' and namespace-uri()='']">
                                    <xsl:variable name="var50_cur" select="."/>
                                    <cbc:AdditionalStreetName>
                                        <xsl:value-of select="."/>
                                    </cbc:AdditionalStreetName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='BlockName' and namespace-uri()='']">
                                    <xsl:variable name="var51_cur" select="."/>
                                    <cbc:BlockName>
                                        <xsl:value-of select="."/>
                                    </cbc:BlockName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='BuildingNumber' and namespace-uri()='']">
                                    <xsl:variable name="var52_cur" select="."/>
                                    <cbc:BuildingNumber>
                                        <xsl:value-of select="."/>
                                    </cbc:BuildingNumber>
                                </xsl:for-each>
                                <cbc:CityName>
                                    <xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='CityName' and namespace-uri()='']"/>
                                </cbc:CityName>
                                <cbc:PostalZone>
                                    <xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='PostalZone' and namespace-uri()='']"/>
                                </cbc:PostalZone>
                                <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='District' and namespace-uri()='']">
                                    <xsl:variable name="var53_cur" select="."/>
                                    <cbc:District>
                                        <xsl:value-of select="."/>
                                    </cbc:District>
                                </xsl:for-each>
                                <cac:AddressLine>
                                    <cbc:Line>
                                        <xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='AddressLine' and namespace-uri()='']"/>
                                    </cbc:Line>
                                </cac:AddressLine>
                                <cac:Country>
                                    <cbc:IdentificationCode>
                                        <xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='IdentificationCode' and namespace-uri()='']"/>
                                    </cbc:IdentificationCode>
                                    <cbc:Name>
                                        <xsl:value-of select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
                                    </cbc:Name>
                                </cac:Country>
                            </cac:RegistrationAddress>
                        </cac:PartyLegalEntity>
                        <xsl:for-each select="*[local-name()='AccountingSupplierParty' and namespace-uri()='']/*[local-name()='Contact' and namespace-uri()='']">
                            <xsl:variable name="var54_cur" select="."/>
                            <cac:Contact>
                                <xsl:for-each select="*[local-name()='Telephone' and namespace-uri()='']">
                                    <xsl:variable name="var55_cur" select="."/>
                                    <cbc:Telephone>
                                        <xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
                                            <xsl:value-of select="."/>
                                        </xsl:if>
                                    </cbc:Telephone>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='Telefax' and namespace-uri()='']">
                                    <xsl:variable name="var56_cur" select="."/>
                                    <cbc:Telefax>
                                        <xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
                                            <xsl:value-of select="."/>
                                        </xsl:if>
                                    </cbc:Telefax>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='ElectronicMail' and namespace-uri()='']">
                                    <xsl:variable name="var57_cur" select="."/>
                                    <cbc:ElectronicMail>
                                        <xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
                                            <xsl:value-of select="."/>
                                        </xsl:if>
                                    </cbc:ElectronicMail>
                                </xsl:for-each>
                            </cac:Contact>
                        </xsl:for-each>
                    </cac:Party>
                </cac:AccountingSupplierParty>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var58_cur" select="."/>
                <cac:AccountingCustomerParty>
                    <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='AdditionalAccountID' and namespace-uri()='']">
                        <xsl:variable name="var59_cur" select="."/>
                        <cbc:AdditionalAccountID>
                            <xsl:value-of select="."/>
                        </cbc:AdditionalAccountID>
                    </xsl:for-each>
                    <cac:Party>
                        <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='WebsiteURL' and namespace-uri()='']">
                            <xsl:variable name="var60_cur" select="."/>
                            <cbc:WebsiteURI>
                                <xsl:value-of select="."/>
                            </cbc:WebsiteURI>
                        </xsl:for-each>
                        <cbc:EndpointID>
                            <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='EndpointID' and namespace-uri()='']/@schemeID">
                                <xsl:variable name="var61_cur" select="."/>
                                <xsl:attribute name="schemeID" namespace="">
                                    <xsl:value-of select="."/>
                                </xsl:attribute>
                            </xsl:for-each>
                            <xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='EndpointID' and namespace-uri()='']"/>
                        </cbc:EndpointID>
                        <cac:PartyIdentification>
                            <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyIdentification' and namespace-uri()='']">
                                <xsl:variable name="var62_cur" select="."/>
                                <cbc:ID>
                                    <xsl:value-of select="."/>
                                </cbc:ID>
                            </xsl:for-each>
                        </cac:PartyIdentification>
                        <cac:PartyName>
                            <cbc:Name>
                                <xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyName' and namespace-uri()='']"/>
                            </cbc:Name>
                        </cac:PartyName>
                        <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PostalAddress' and namespace-uri()='']">
                            <xsl:variable name="var63_cur" select="."/>
                            <cac:PostalAddress>
                                <xsl:for-each select="*[local-name()='Floor' and namespace-uri()='']">
                                    <xsl:variable name="var64_cur" select="."/>
                                    <cbc:Floor>
                                        <xsl:value-of select="."/>
                                    </cbc:Floor>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='Room' and namespace-uri()='']">
                                    <xsl:variable name="var65_cur" select="."/>
                                    <cbc:Room>
                                        <xsl:value-of select="."/>
                                    </cbc:Room>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='StreetName' and namespace-uri()='']">
                                    <xsl:variable name="var66_cur" select="."/>
                                    <cbc:StreetName>
                                        <xsl:value-of select="."/>
                                    </cbc:StreetName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AdditionalStreetName' and namespace-uri()='']">
                                    <xsl:variable name="var67_cur" select="."/>
                                    <cbc:AdditionalStreetName>
                                        <xsl:value-of select="."/>
                                    </cbc:AdditionalStreetName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='BlockName' and namespace-uri()='']">
                                    <xsl:variable name="var68_cur" select="."/>
                                    <cbc:BlockName>
                                        <xsl:value-of select="."/>
                                    </cbc:BlockName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='BuildingNumber' and namespace-uri()='']">
                                    <xsl:variable name="var69_cur" select="."/>
                                    <cbc:BuildingNumber>
                                        <xsl:value-of select="."/>
                                    </cbc:BuildingNumber>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='CityName' and namespace-uri()='']">
                                    <xsl:variable name="var70_cur" select="."/>
                                    <cbc:CityName>
                                        <xsl:value-of select="."/>
                                    </cbc:CityName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='PostalZone' and namespace-uri()='']">
                                    <xsl:variable name="var71_cur" select="."/>
                                    <cbc:PostalZone>
                                        <xsl:value-of select="."/>
                                    </cbc:PostalZone>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='District' and namespace-uri()='']">
                                    <xsl:variable name="var72_cur" select="."/>
                                    <cbc:District>
                                        <xsl:value-of select="."/>
                                    </cbc:District>
                                </xsl:for-each>
                                <cac:AddressLine>
                                    <xsl:for-each select="*[local-name()='AddressLine' and namespace-uri()='']">
                                        <xsl:variable name="var73_cur" select="."/>
                                        <cbc:Line>
                                            <xsl:value-of select="."/>
                                        </cbc:Line>
                                    </xsl:for-each>
                                </cac:AddressLine>
                                <xsl:for-each select="*[local-name()='Country' and namespace-uri()='']">
                                    <xsl:variable name="var74_cur" select="."/>
                                    <cac:Country>
                                        <cbc:IdentificationCode>
                                            <xsl:value-of select="*[local-name()='IdentificationCode' and namespace-uri()='']"/>
                                        </cbc:IdentificationCode>
                                        <cbc:Name>
                                            <xsl:value-of select="*[local-name()='Name' and namespace-uri()='']"/>
                                        </cbc:Name>
                                    </cac:Country>
                                </xsl:for-each>
                            </cac:PostalAddress>
                        </xsl:for-each>
                        <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyTaxScheme' and namespace-uri()='']">
                            <xsl:variable name="var75_cur" select="."/>
                            <cac:PartyTaxScheme>
                                <xsl:for-each select="*[local-name()='CompanyID' and namespace-uri()='']">
                                    <xsl:variable name="var76_cur" select="."/>
                                    <cbc:CompanyID>
                                        <xsl:value-of select="."/>
                                    </cbc:CompanyID>
                                </xsl:for-each>
                                <cac:TaxScheme>
                                    <cbc:ID>
                                        <xsl:value-of select="*[local-name()='TaxScheme' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
                                    </cbc:ID>
                                </cac:TaxScheme>
                            </cac:PartyTaxScheme>
                        </xsl:for-each>
                        <cac:PartyLegalEntity>
                            <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationName' and namespace-uri()='']">
                                <xsl:variable name="var77_cur" select="."/>
                                <cbc:RegistrationName>
                                    <xsl:value-of select="."/>
                                </cbc:RegistrationName>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='CompanyID' and namespace-uri()='']">
                                <xsl:variable name="var78_cur" select="."/>
                                <cbc:CompanyID>
                                    <xsl:value-of select="."/>
                                </cbc:CompanyID>
                            </xsl:for-each>
                            <cac:RegistrationAddress>
                                <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Floor' and namespace-uri()='']">
                                    <xsl:variable name="var79_cur" select="."/>
                                    <cbc:Floor>
                                        <xsl:value-of select="."/>
                                    </cbc:Floor>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Room' and namespace-uri()='']">
                                    <xsl:variable name="var80_cur" select="."/>
                                    <cbc:Room>
                                        <xsl:value-of select="."/>
                                    </cbc:Room>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='StreetName' and namespace-uri()='']">
                                    <xsl:variable name="var81_cur" select="."/>
                                    <cbc:StreetName>
                                        <xsl:value-of select="."/>
                                    </cbc:StreetName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='AdditionalStreetName' and namespace-uri()='']">
                                    <xsl:variable name="var82_cur" select="."/>
                                    <cbc:AdditionalStreetName>
                                        <xsl:value-of select="."/>
                                    </cbc:AdditionalStreetName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='BlockName' and namespace-uri()='']">
                                    <xsl:variable name="var83_cur" select="."/>
                                    <cbc:BlockName>
                                        <xsl:value-of select="."/>
                                    </cbc:BlockName>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='BuildingNumber' and namespace-uri()='']">
                                    <xsl:variable name="var84_cur" select="."/>
                                    <cbc:BuildingNumber>
                                        <xsl:value-of select="."/>
                                    </cbc:BuildingNumber>
                                </xsl:for-each>
                                <cbc:CityName>
                                    <xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='CityName' and namespace-uri()='']"/>
                                </cbc:CityName>
                                <cbc:PostalZone>
                                    <xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='PostalZone' and namespace-uri()='']"/>
                                </cbc:PostalZone>
                                <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='District' and namespace-uri()='']">
                                    <xsl:variable name="var85_cur" select="."/>
                                    <cbc:District>
                                        <xsl:value-of select="."/>
                                    </cbc:District>
                                </xsl:for-each>
                                <cac:AddressLine>
                                    <cbc:Line>
                                        <xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='AddressLine' and namespace-uri()='']"/>
                                    </cbc:Line>
                                </cac:AddressLine>
                                <cac:Country>
                                    <cbc:IdentificationCode>
                                        <xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='IdentificationCode' and namespace-uri()='']"/>
                                    </cbc:IdentificationCode>
                                    <cbc:Name>
                                        <xsl:value-of select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='PartyLegalEntity' and namespace-uri()='']/*[local-name()='RegistrationAddress' and namespace-uri()='']/*[local-name()='Country' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
                                    </cbc:Name>
                                </cac:Country>
                            </cac:RegistrationAddress>
                        </cac:PartyLegalEntity>
                        <xsl:for-each select="*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='Contact' and namespace-uri()='']">
                            <xsl:variable name="var86_cur" select="."/>
                            <cac:Contact>
                                <xsl:for-each select="*[local-name()='Telephone' and namespace-uri()='']">
                                    <xsl:variable name="var87_cur" select="."/>
                                    <cbc:Telephone>
                                        <xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
                                            <xsl:value-of select="."/>
                                        </xsl:if>
                                    </cbc:Telephone>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='Telefax' and namespace-uri()='']">
                                    <xsl:variable name="var88_cur" select="."/>
                                    <cbc:Telefax>
                                        <xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
                                            <xsl:value-of select="."/>
                                        </xsl:if>
                                    </cbc:Telefax>
                                </xsl:for-each>
                                <xsl:for-each select="*[local-name()='ElectronicMail' and namespace-uri()='']">
                                    <xsl:variable name="var89_cur" select="."/>
                                    <cbc:ElectronicMail>
                                        <xsl:if test="not((translate(@xsi:nil, 'true ', '1') = '1'))">
                                            <xsl:value-of select="."/>
                                        </xsl:if>
                                    </cbc:ElectronicMail>
                                </xsl:for-each>
                            </cac:Contact>
                        </xsl:for-each>
                    </cac:Party>
                </cac:AccountingCustomerParty>
            </xsl:for-each>
            <cac:Delivery>
                <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='AccountingCustomerParty' and namespace-uri()='']/*[local-name()='DeliveryAddress' and namespace-uri()='']">
                    <xsl:variable name="var90_cur" select="."/>
                    <cac:DeliveryAddress>
                        <xsl:for-each select="*[local-name()='Floor' and namespace-uri()='']">
                            <xsl:variable name="var91_cur" select="."/>
                            <cbc:Floor>
                                <xsl:value-of select="."/>
                            </cbc:Floor>
                        </xsl:for-each>
                        <xsl:for-each select="*[local-name()='Room' and namespace-uri()='']">
                            <xsl:variable name="var92_cur" select="."/>
                            <cbc:Room>
                                <xsl:value-of select="."/>
                            </cbc:Room>
                        </xsl:for-each>
                        <xsl:for-each select="*[local-name()='StreetName' and namespace-uri()='']">
                            <xsl:variable name="var93_cur" select="."/>
                            <cbc:StreetName>
                                <xsl:value-of select="."/>
                            </cbc:StreetName>
                        </xsl:for-each>
                        <xsl:for-each select="*[local-name()='AdditionalStreetName' and namespace-uri()='']">
                            <xsl:variable name="var94_cur" select="."/>
                            <cbc:AdditionalStreetName>
                                <xsl:value-of select="."/>
                            </cbc:AdditionalStreetName>
                        </xsl:for-each>
                        <xsl:for-each select="*[local-name()='BlockName' and namespace-uri()='']">
                            <xsl:variable name="var95_cur" select="."/>
                            <cbc:BlockName>
                                <xsl:value-of select="."/>
                            </cbc:BlockName>
                        </xsl:for-each>
                        <xsl:for-each select="*[local-name()='BuildingNumber' and namespace-uri()='']">
                            <xsl:variable name="var96_cur" select="."/>
                            <cbc:BuildingNumber>
                                <xsl:value-of select="."/>
                            </cbc:BuildingNumber>
                        </xsl:for-each>
                        <cbc:CityName>
                            <xsl:value-of select="*[local-name()='CityName' and namespace-uri()='']"/>
                        </cbc:CityName>
                        <cbc:PostalZone>
                            <xsl:value-of select="*[local-name()='PostalZone' and namespace-uri()='']"/>
                        </cbc:PostalZone>
                        <xsl:for-each select="*[local-name()='District' and namespace-uri()='']">
                            <xsl:variable name="var97_cur" select="."/>
                            <cbc:District>
                                <xsl:value-of select="."/>
                            </cbc:District>
                        </xsl:for-each>
                        <cac:AddressLine>
                            <cbc:Line>
                                <xsl:value-of select="*[local-name()='AddressLine' and namespace-uri()='']"/>
                            </cbc:Line>
                        </cac:AddressLine>
                        <cac:Country>
                            <cbc:IdentificationCode>
                                <xsl:value-of select="*[local-name()='Country' and namespace-uri()='']/*[local-name()='IdentificationCode' and namespace-uri()='']"/>
                            </cbc:IdentificationCode>
                            <cbc:Name>
                                <xsl:value-of select="*[local-name()='Country' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
                            </cbc:Name>
                        </cac:Country>
                    </cac:DeliveryAddress>
                </xsl:for-each>
            </cac:Delivery>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var98_cur" select="."/>
                <cac:PaymentMeans>
                    <cbc:PaymentMeansCode>
                        <xsl:value-of select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PaymentMeansCode' and namespace-uri()='']"/>
                    </cbc:PaymentMeansCode>
                    <xsl:for-each select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayerFinancialAccount' and namespace-uri()='']">
                        <xsl:variable name="var99_cur" select="."/>
                        <cac:PayerFinancialAccount>
                            <xsl:for-each select="*[local-name()='ID' and namespace-uri()='']">
                                <xsl:variable name="var100_cur" select="."/>
                                <cbc:ID>
                                    <xsl:value-of select="."/>
                                </cbc:ID>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='Name' and namespace-uri()='']">
                                <xsl:variable name="var101_cur" select="."/>
                                <cbc:Name>
                                    <xsl:value-of select="."/>
                                </cbc:Name>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='CurrencyCode' and namespace-uri()='']">
                                <xsl:variable name="var102_cur" select="."/>
                                <cbc:CurrencyCode>
                                    <xsl:value-of select="."/>
                                </cbc:CurrencyCode>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='FinancialInstitutionBranch' and namespace-uri()='']">
                                <xsl:variable name="var103_cur" select="."/>
                                <cac:FinancialInstitutionBranch>
                                    <xsl:for-each select="*[local-name()='ID' and namespace-uri()='']">
                                        <xsl:variable name="var104_cur" select="."/>
                                        <cbc:ID>
                                            <xsl:value-of select="."/>
                                        </cbc:ID>
                                    </xsl:for-each>
                                    <xsl:for-each select="*[local-name()='Name' and namespace-uri()='']">
                                        <xsl:variable name="var105_cur" select="."/>
                                        <cbc:Name>
                                            <xsl:value-of select="."/>
                                        </cbc:Name>
                                    </xsl:for-each>
                                </cac:FinancialInstitutionBranch>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='Country' and namespace-uri()='']">
                                <xsl:variable name="var106_cur" select="."/>
                                <cac:Country>
                                    <xsl:for-each select="*[local-name()='IdentificationCode' and namespace-uri()='']">
                                        <xsl:variable name="var107_cur" select="."/>
                                        <cbc:IdentificationCode>
                                            <xsl:value-of select="."/>
                                        </cbc:IdentificationCode>
                                    </xsl:for-each>
                                    <xsl:for-each select="*[local-name()='Name' and namespace-uri()='']">
                                        <xsl:variable name="var108_cur" select="."/>
                                        <cbc:Name>
                                            <xsl:value-of select="."/>
                                        </cbc:Name>
                                    </xsl:for-each>
                                </cac:Country>
                            </xsl:for-each>
                        </cac:PayerFinancialAccount>
                    </xsl:for-each>
                    <xsl:for-each select="*[local-name()='PaymentMeans' and namespace-uri()='']/*[local-name()='PayeeFinancialAccount' and namespace-uri()='']">
                        <xsl:variable name="var109_cur" select="."/>
                        <cac:PayeeFinancialAccount>
                            <xsl:for-each select="*[local-name()='ID' and namespace-uri()='']">
                                <xsl:variable name="var110_cur" select="."/>
                                <cbc:ID>
                                    <xsl:value-of select="."/>
                                </cbc:ID>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='Name' and namespace-uri()='']">
                                <xsl:variable name="var111_cur" select="."/>
                                <cbc:Name>
                                    <xsl:value-of select="."/>
                                </cbc:Name>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='CurrencyCode' and namespace-uri()='']">
                                <xsl:variable name="var112_cur" select="."/>
                                <cbc:CurrencyCode>
                                    <xsl:value-of select="."/>
                                </cbc:CurrencyCode>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='FinancialInstitutionBranch' and namespace-uri()='']">
                                <xsl:variable name="var113_cur" select="."/>
                                <cac:FinancialInstitutionBranch>
                                    <xsl:for-each select="*[local-name()='ID' and namespace-uri()='']">
                                        <xsl:variable name="var114_cur" select="."/>
                                        <cbc:ID>
                                            <xsl:value-of select="."/>
                                        </cbc:ID>
                                    </xsl:for-each>
                                    <xsl:for-each select="*[local-name()='Name' and namespace-uri()='']">
                                        <xsl:variable name="var115_cur" select="."/>
                                        <cbc:Name>
                                            <xsl:value-of select="."/>
                                        </cbc:Name>
                                    </xsl:for-each>
                                </cac:FinancialInstitutionBranch>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='Country' and namespace-uri()='']">
                                <xsl:variable name="var116_cur" select="."/>
                                <cac:Country>
                                    <cbc:IdentificationCode>
                                        <xsl:value-of select="*[local-name()='IdentificationCode' and namespace-uri()='']"/>
                                    </cbc:IdentificationCode>
                                    <cbc:Name>
                                        <xsl:value-of select="*[local-name()='Name' and namespace-uri()='']"/>
                                    </cbc:Name>
                                </cac:Country>
                            </xsl:for-each>
                        </cac:PayeeFinancialAccount>
                    </xsl:for-each>
                </cac:PaymentMeans>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var117_cur" select="."/>
                <cac:PricingExchangeRate>
                    <cbc:SourceCurrencyCode>
                        <xsl:value-of select="*[local-name()='PricingExchangeRate' and namespace-uri()='']/*[local-name()='SourceCurrencyCode' and namespace-uri()='']"/>
                    </cbc:SourceCurrencyCode>
                    <cbc:TargetCurrencyCode>
                        <xsl:value-of select="*[local-name()='PricingExchangeRate' and namespace-uri()='']/*[local-name()='TargetCurrencyCode' and namespace-uri()='']"/>
                    </cbc:TargetCurrencyCode>
                    <cbc:CalculationRate>
                        <xsl:value-of select="number(*[local-name()='PricingExchangeRate' and namespace-uri()='']/*[local-name()='CalculationRate' and namespace-uri()=''])"/>
                    </cbc:CalculationRate>
                    <cbc:MathematicOperatorCode>
                        <xsl:value-of select="*[local-name()='PricingExchangeRate' and namespace-uri()='']/*[local-name()='MathematicOperatorCode' and namespace-uri()='']"/>
                    </cbc:MathematicOperatorCode>
                </cac:PricingExchangeRate>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var118_cur" select="."/>
                <cac:TaxTotal>
                    <cbc:TaxAmount>
                        <xsl:for-each select="*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxSubtotal' and namespace-uri()='']">
                            <xsl:variable name="var119_cur" select="."/>
                            <xsl:attribute name="currencyID" namespace="">
                                <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                            </xsl:attribute>
                        </xsl:for-each>
                        <xsl:value-of select="number(*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxAmount' and namespace-uri()=''])"/>
                    </cbc:TaxAmount>
                    <xsl:for-each select="*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxSubtotal' and namespace-uri()='']">
                        <xsl:variable name="var120_cur" select="."/>
                        <cac:TaxSubtotal>
                            <cbc:TaxableAmount>
                                <xsl:attribute name="currencyID" namespace="">
                                    <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                                </xsl:attribute>
                                <xsl:value-of select="number(*[local-name()='TaxableAmount' and namespace-uri()=''])"/>
                            </cbc:TaxableAmount>
                            <cbc:TaxAmount>
                                <xsl:attribute name="currencyID" namespace="">
                                    <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                                </xsl:attribute>
                                <xsl:value-of select="round((*[local-name()='TaxableAmount' and namespace-uri()=''] * (*[local-name()='Percent' and namespace-uri()=''] div 100)))"/>
                            </cbc:TaxAmount>
                            <cbc:Percent>
                                <xsl:value-of select="number(*[local-name()='Percent' and namespace-uri()=''])"/>
                            </cbc:Percent>
                            <cac:TaxCategory>
                                <cbc:ID>
                                    <xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
                                </cbc:ID>
                                <cbc:Name>
                                    <xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
                                </cbc:Name>
                                <cbc:Percent>
                                    <xsl:value-of select="number(*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='Percent' and namespace-uri()=''])"/>
                                </cbc:Percent>
                                <cac:TaxScheme>
                                    <cbc:ID>
                                        <xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='TaxScheme' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
                                    </cbc:ID>
                                </cac:TaxScheme>
                            </cac:TaxCategory>
                        </cac:TaxSubtotal>
                    </xsl:for-each>
                </cac:TaxTotal>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']">
                <xsl:variable name="var121_cur" select="."/>
                <cac:LegalMonetaryTotal>
                    <cbc:LineExtensionAmount>
                        <xsl:for-each select="*[local-name()='LegalMonetaryTotal' and namespace-uri()='']/*[local-name()='LineExtensionAmount' and namespace-uri()='']/@CurrencyID">
                            <xsl:variable name="var122_cur" select="."/>
                            <xsl:attribute name="currencyID" namespace="">
                                <xsl:value-of select="."/>
                            </xsl:attribute>
                        </xsl:for-each>
                        <xsl:value-of select="number(*[local-name()='LegalMonetaryTotal' and namespace-uri()='']/*[local-name()='LineExtensionAmount' and namespace-uri()=''])"/>
                    </cbc:LineExtensionAmount>
                    <cbc:TaxExclusiveAmount>
                        <xsl:for-each select="*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxSubtotal' and namespace-uri()='']">
                            <xsl:variable name="var123_cur" select="."/>
                            <xsl:attribute name="currencyID" namespace="">
                                <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                            </xsl:attribute>
                        </xsl:for-each>
                        <xsl:value-of select="number(*[local-name()='LegalMonetaryTotal' and namespace-uri()='']/*[local-name()='TaxExclusiveAmount' and namespace-uri()=''])"/>
                    </cbc:TaxExclusiveAmount>
                    <cbc:TaxInclusiveAmount>
                        <xsl:for-each select="*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxSubtotal' and namespace-uri()='']">
                            <xsl:variable name="var124_cur" select="."/>
                            <xsl:attribute name="currencyID" namespace="">
                                <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                            </xsl:attribute>
                        </xsl:for-each>
                        <xsl:value-of select="number(*[local-name()='LegalMonetaryTotal' and namespace-uri()='']/*[local-name()='TaxInclusiveAmount' and namespace-uri()=''])"/>
                    </cbc:TaxInclusiveAmount>
                    <cbc:PayableAmount>
                        <xsl:for-each select="*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxSubtotal' and namespace-uri()='']">
                            <xsl:variable name="var125_cur" select="."/>
                            <xsl:attribute name="currencyID" namespace="">
                                <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                            </xsl:attribute>
                        </xsl:for-each>
                        <xsl:value-of select="number(*[local-name()='LegalMonetaryTotal' and namespace-uri()='']/*[local-name()='PayableAmount' and namespace-uri()=''])"/>
                    </cbc:PayableAmount>
                </cac:LegalMonetaryTotal>
            </xsl:for-each>
            <xsl:for-each select="*[local-name()='BavInvoice' and namespace-uri()='']/*[local-name()='InvoiceLine' and namespace-uri()='']">
                <xsl:variable name="var126_cur" select="."/>
                <cac:InvoiceLine>
                    <cbc:ID>
                        <xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
                    </cbc:ID>
                    <cbc:InvoicedQuantity>
                        <xsl:variable name="var127_nested">
                            <xsl:call-template name="vmf:vmf3_inputtoresult">
                                <xsl:with-param name="input" select="string(*[local-name()='UnitCode' and namespace-uri()=''])"/>
                            </xsl:call-template>
                        </xsl:variable>
                        <xsl:if test="string($var127_nested)">
                            <xsl:attribute name="unitCode" namespace="">
                                <xsl:variable name="var128_nested">
                                    <xsl:call-template name="vmf:vmf3_inputtoresult">
                                        <xsl:with-param name="input" select="string(*[local-name()='UnitCode' and namespace-uri()=''])"/>
                                    </xsl:call-template>
                                </xsl:variable>
                                <xsl:value-of select="substring($var128_nested, 2)"/>
                            </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="number(*[local-name()='InvoicedQuantity' and namespace-uri()=''])"/>
                    </cbc:InvoicedQuantity>
                    <cbc:LineExtensionAmount>
                        <xsl:for-each select="*[local-name()='LineExtensionAmount' and namespace-uri()='']/@CurrencyID">
                            <xsl:variable name="var129_cur" select="."/>
                            <xsl:attribute name="currencyID" namespace="">
                                <xsl:value-of select="."/>
                            </xsl:attribute>
                        </xsl:for-each>
                        <xsl:value-of select="number(*[local-name()='LineExtensionAmount' and namespace-uri()=''])"/>
                    </cbc:LineExtensionAmount>
                    <xsl:for-each select="*[local-name()='TaxPointDate' and namespace-uri()='']">
                        <xsl:variable name="var130_cur" select="."/>
                        <cbc:TaxPointDate>
                            <xsl:value-of select="."/>
                        </cbc:TaxPointDate>
                    </xsl:for-each>
                    <xsl:for-each select="*[local-name()='InvoicePeriod' and namespace-uri()='']">
                        <xsl:variable name="var131_cur" select="."/>
                        <cac:InvoicePeriod>
                            <xsl:for-each select="*[local-name()='StartDate' and namespace-uri()='']">
                                <xsl:variable name="var132_cur" select="."/>
                                <cbc:StartDate>
                                    <xsl:value-of select="."/>
                                </cbc:StartDate>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='EndDate' and namespace-uri()='']">
                                <xsl:variable name="var133_cur" select="."/>
                                <cbc:EndDate>
                                    <xsl:value-of select="."/>
                                </cbc:EndDate>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='Description' and namespace-uri()='']">
                                <xsl:variable name="var134_cur" select="."/>
                                <cbc:Description>
                                    <xsl:value-of select="."/>
                                </cbc:Description>
                            </xsl:for-each>
                        </cac:InvoicePeriod>
                    </xsl:for-each>
                    <xsl:for-each select="*[local-name()='BillingReference' and namespace-uri()='']">
                        <xsl:variable name="var135_cur" select="."/>
                        <cac:BillingReference>
                            <xsl:for-each select="*[local-name()='InvoiceDocumentReference' and namespace-uri()='']">
                                <xsl:variable name="var136_cur" select="."/>
                                <cac:InvoiceDocumentReference>
                                    <cbc:ID>
                                        <xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
                                    </cbc:ID>
                                    <cbc:DocumentDescription>
                                        <xsl:value-of select="*[local-name()='DocumentDescription' and namespace-uri()='']"/>
                                    </cbc:DocumentDescription>
                                </cac:InvoiceDocumentReference>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='BillingReferenceLine' and namespace-uri()='']">
                                <xsl:variable name="var137_cur" select="."/>
                                <cac:BillingReferenceLine>
                                    <cbc:ID>
                                        <xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
                                    </cbc:ID>
                                </cac:BillingReferenceLine>
                            </xsl:for-each>
                        </cac:BillingReference>
                    </xsl:for-each>
                    <xsl:for-each select="*[local-name()='PaymentTerms' and namespace-uri()='']">
                        <xsl:variable name="var138_cur" select="."/>
                        <cac:PaymentTerms>
                            <cbc:Note>
                                <xsl:value-of select="*[local-name()='Note' and namespace-uri()='']"/>
                            </cbc:Note>
                        </cac:PaymentTerms>
                    </xsl:for-each>
                    <xsl:for-each select="*[local-name()='AllowanceCharge' and namespace-uri()='']">
                        <xsl:variable name="var139_cur" select="."/>
                        <cac:AllowanceCharge>
                            <xsl:for-each select="*[local-name()='ChargeIndicator' and namespace-uri()='']">
                                <xsl:variable name="var140_cur" select="."/>
                                <cbc:ChargeIndicator>
                                    <xsl:value-of select="boolean(translate(normalize-space(string(.)), ' 0false', ''))"/>
                                </cbc:ChargeIndicator>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='AllowanceChargeReason' and namespace-uri()='']">
                                <xsl:variable name="var141_cur" select="."/>
                                <cbc:AllowanceChargeReason>
                                    <xsl:value-of select="."/>
                                </cbc:AllowanceChargeReason>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='MultiplierFactorNumeric' and namespace-uri()='']">
                                <xsl:variable name="var142_cur" select="."/>
                                <cbc:MultiplierFactorNumeric>
                                    <xsl:value-of select="number(.)"/>
                                </cbc:MultiplierFactorNumeric>
                            </xsl:for-each>
                            <xsl:for-each select="*[local-name()='Amount' and namespace-uri()='']">
                                <xsl:variable name="var143_cur" select="."/>
                                <cbc:Amount>
                                    <xsl:for-each select="$var126_cur/*[local-name()='TaxTotal' and namespace-uri()='']/*[local-name()='TaxSubtotal' and namespace-uri()='']">
                                        <xsl:variable name="var144_cur" select="."/>
                                        <xsl:attribute name="currencyID" namespace="">
                                            <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                                        </xsl:attribute>
                                    </xsl:for-each>
                                    <xsl:value-of select="number(.)"/>
                                </cbc:Amount>
                            </xsl:for-each>
                        </cac:AllowanceCharge>
                    </xsl:for-each>
                    <xsl:for-each select="*[local-name()='TaxTotal' and namespace-uri()='']">
                        <xsl:variable name="var145_cur" select="."/>
                        <cac:TaxTotal>
                            <cbc:TaxAmount>
                                <xsl:for-each select="*[local-name()='TaxSubtotal' and namespace-uri()='']">
                                    <xsl:variable name="var146_cur" select="."/>
                                    <xsl:attribute name="currencyID" namespace="">
                                        <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                                    </xsl:attribute>
                                </xsl:for-each>
                                <xsl:value-of select="number(*[local-name()='TaxAmount' and namespace-uri()=''])"/>
                            </cbc:TaxAmount>
                            <xsl:for-each select="*[local-name()='TaxSubtotal' and namespace-uri()='']">
                                <xsl:variable name="var147_cur" select="."/>
                                <cac:TaxSubtotal>
                                    <cbc:TaxableAmount>
                                        <xsl:attribute name="currencyID" namespace="">
                                            <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                                        </xsl:attribute>
                                        <xsl:value-of select="number(*[local-name()='TaxableAmount' and namespace-uri()=''])"/>
                                    </cbc:TaxableAmount>
                                    <cbc:TaxAmount>
                                        <xsl:attribute name="currencyID" namespace="">
                                            <xsl:value-of select="*[local-name()='CurrencyID' and namespace-uri()='']"/>
                                        </xsl:attribute>
                                        <xsl:value-of select="round(*[local-name()='TaxAmount' and namespace-uri()=''])"/>
                                    </cbc:TaxAmount>
                                    <cbc:Percent>
                                        <xsl:value-of select="number(*[local-name()='Percent' and namespace-uri()=''])"/>
                                    </cbc:Percent>
                                    <cac:TaxCategory>
                                        <cbc:ID>
                                            <xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
                                        </cbc:ID>
                                        <cbc:Name>
                                            <xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
                                        </cbc:Name>
                                        <cbc:Percent>
                                            <xsl:value-of select="number(*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='Percent' and namespace-uri()=''])"/>
                                        </cbc:Percent>
                                        <cac:TaxScheme>
                                            <cbc:ID>
                                                <xsl:value-of select="*[local-name()='TaxCategory' and namespace-uri()='']/*[local-name()='TaxScheme' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
                                            </cbc:ID>
                                        </cac:TaxScheme>
                                    </cac:TaxCategory>
                                </cac:TaxSubtotal>
                            </xsl:for-each>
                        </cac:TaxTotal>
                    </xsl:for-each>
                    <cac:Item>
                        <cbc:Name>
                            <xsl:value-of select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
                        </cbc:Name>
                        <xsl:for-each select="*[local-name()='AdditionalInformation' and namespace-uri()='']">
                            <xsl:variable name="var148_cur" select="."/>
                            <cbc:AdditionalInformation>
                                <xsl:value-of select="."/>
                            </cbc:AdditionalInformation>
                        </xsl:for-each>
                        <xsl:for-each select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='SellersItemIdentification' and namespace-uri()='']">
                            <xsl:variable name="var149_cur" select="."/>
                            <cac:SellersItemIdentification>
                                <xsl:for-each select="*[local-name()='ID' and namespace-uri()='']">
                                    <xsl:variable name="var150_cur" select="."/>
                                    <cbc:ID>
                                        <xsl:value-of select="."/>
                                    </cbc:ID>
                                </xsl:for-each>
                            </cac:SellersItemIdentification>
                        </xsl:for-each>
                        <cac:ClassifiedTaxCategory>
                            <cbc:ID>
                                <xsl:value-of select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='ClassifiedTaxCategory' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
                            </cbc:ID>
                            <cbc:Name>
                                <xsl:value-of select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='ClassifiedTaxCategory' and namespace-uri()='']/*[local-name()='Name' and namespace-uri()='']"/>
                            </cbc:Name>
                            <cbc:Percent>
                                <xsl:value-of select="number(*[local-name()='Item' and namespace-uri()='']/*[local-name()='ClassifiedTaxCategory' and namespace-uri()='']/*[local-name()='Percent' and namespace-uri()=''])"/>
                            </cbc:Percent>
                            <cac:TaxScheme>
                                <cbc:ID>
                                    <xsl:value-of select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='ClassifiedTaxCategory' and namespace-uri()='']/*[local-name()='TaxScheme' and namespace-uri()='']/*[local-name()='ID' and namespace-uri()='']"/>
                                </cbc:ID>
                            </cac:TaxScheme>
                        </cac:ClassifiedTaxCategory>
                        <xsl:for-each select="*[local-name()='Item' and namespace-uri()='']/*[local-name()='AdditionalItemProperty' and namespace-uri()='']">
                            <xsl:variable name="var151_cur" select="."/>
                            <cac:AdditionalItemProperty>
                                <cbc:ID>
                                    <xsl:value-of select="*[local-name()='ID' and namespace-uri()='']"/>
                                </cbc:ID>
                                <cbc:Name>
                                    <xsl:value-of select="*[local-name()='Name' and namespace-uri()='']"/>
                                </cbc:Name>
                                <cbc:Value>
                                    <xsl:value-of select="*[local-name()='Value' and namespace-uri()='']"/>
                                </cbc:Value>
                            </cac:AdditionalItemProperty>
                        </xsl:for-each>
                    </cac:Item>
                    <cac:Price>
                        <cbc:PriceAmount>
                            <xsl:attribute name="currencyID" namespace="">
                                <xsl:value-of select="*[local-name()='Price' and namespace-uri()='']/*[local-name()='CurrencyID' and namespace-uri()='']"/>
                            </xsl:attribute>
                            <xsl:value-of select="number(*[local-name()='Price' and namespace-uri()='']/*[local-name()='PriceAmount' and namespace-uri()=''])"/>
                        </cbc:PriceAmount>
                        <cbc:BaseQuantity>
                            <xsl:variable name="var152_nested">
                                <xsl:call-template name="vmf:vmf3_inputtoresult">
                                    <xsl:with-param name="input" select="string(*[local-name()='UnitCode' and namespace-uri()=''])"/>
                                </xsl:call-template>
                            </xsl:variable>
                            <xsl:if test="string($var152_nested)">
                                <xsl:attribute name="unitCode" namespace="">
                                    <xsl:variable name="var153_nested">
                                        <xsl:call-template name="vmf:vmf3_inputtoresult">
                                            <xsl:with-param name="input" select="string(*[local-name()='UnitCode' and namespace-uri()=''])"/>
                                        </xsl:call-template>
                                    </xsl:variable>
                                    <xsl:value-of select="substring($var153_nested, 2)"/>
                                </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="number(*[local-name()='Price' and namespace-uri()='']/*[local-name()='BaseQuantity' and namespace-uri()=''])"/>
                        </cbc:BaseQuantity>
                    </cac:Price>
                </cac:InvoiceLine>
            </xsl:for-each>
        </Invoice>
    </xsl:template>
</xsl:stylesheet>
