Flexibill\NavBundle\Model\Header:
    cdata: false
    exclusion_policy: ALL
    properties:
         requestId:
            name: requestId
            serialized_name: requestId
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         timestamp:
            name: timestamp
            serialized_name: timestamp
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         requestVersion:
            name: requestVersion
            serialized_name: requestVersion
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         headerVersion:
            name: headerVersion
            serialized_name: headerVersion
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]
