Flexibill\NavBundle\Model\ManageInvoiceRequest:
    xml_root_name: ManageInvoiceRequest
    xml_root_namespace: http://schemas.nav.gov.hu/OSA/3.0/api
    xml_namespaces:
        "common": "http://schemas.nav.gov.hu/NTCA/1.0/common"
    cdata: false
    exclusion_policy: ALL
    accessor_order: custom
    custom_accessor_order: [header, user, software, exchangeToken, invoiceOperations]
    properties:
         header:
            name: header
            serialized_name: common:header
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         user:
            name: user
            serialized_name: common:user
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         software:
            name: software
            serialized_name: software
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         exchangeToken:
            name: exchangeToken
            serialized_name: exchangeToken
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         invoiceOperations:
            name: invoiceOperations
            serialized_name: invoiceOperations
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]
