Flexibill\NavBundle\Model\BusinessValidationResult:
    cdata: false
    exclusion_policy: ALL
    properties:
         validationResultCode:
            name: validationResultCode
            serialized_name: validationResultCode
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         validationErrorCode:
            name: validationErrorCode
            serialized_name: validationErrorCode
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         message:
            name: message
            serialized_name: message
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         pointer:
            name: pointer
            serialized_name: pointer
            type: Flexibill\NavBundle\Model\Pointer
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]