Flexibill\NavBundle\Model\ProcessingResult:
    cdata: false
    exclusion_policy: ALL
    properties:
         index:
            name: index
            serialized_name: index
            type: integer
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         invoiceStatus:
            name: invoiceStatus
            serialized_name: invoiceStatus
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         technicalValidationMessages:
            name: technicalValidationMessages
            serialized_name: technicalValidationMessages
            expose: true
            skip_when_empty: true
            type: ArrayCollection<Flexibill\NavBundle\Model\TechnicalValidationResult>
            xml_list:
                inline: true
                entry_name: technicalValidationMessages
            groups: [short, long, specific]

         businessValidationMessages:
            name: businessValidationMessages
            serialized_name: businessValidationMessages
            expose: true
            skip_when_empty: true
            type: ArrayCollection<Flexibill\NavBundle\Model\BusinessValidationResult>
            xml_list:
                inline: true
                entry_name: businessValidationMessages
            groups: [short, long, specific]

         compressedContentIndicator:
            name: compressedContentIndicator
            serialized_name: compressedContentIndicator
            type: boolean
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         originalRequest:
            name: originalRequest
            serialized_name: originalRequest
            type: boolean
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]