Flexibill\NavBundle\Model\InvoiceOperation:
    cdata: false
    exclusion_policy: ALL
    properties:
         index:
            name: index
            serialized_name: index
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         operation:
            name: operation
            serialized_name: invoiceOperation
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]

         invoice:
            name: invoice
            serialized_name: invoiceData
            type: string
            expose: true
            skip_when_empty: true
            xml_element:
                cdata: false
            groups: [short, long, specific]
